### ISSUE TITLE
With last core in NUC Installation, freezes the PC

### ISSUE THREAD

**Issue by Sergi-CP** [networkupstools/nut#1013]
Hi, this integration works fine since last core update. Now when I try to start the server, home assistant crashes and won't start.

**Comment by jimklimov** [comment]
Hello, can you please elaborate on how this issue relates to NUT? (logs, setup details...) :)

Note this project is not behind NUC, nor HomeAssistant, nor even its plugin which wraps NUT. During recent weeks I've seen several discussions about HA module for NUT however, so maybe contacting its developer would help better. Also if they published specific NUT source version used to product the package (I believe it is a private combo of patches over some branch of NUT), it could help nail some issues too.
