### ISSUE TITLE
[HCL]<Salicru> <TWINPRO3/TWINRT3> supported by <hid_usb >

### ISSUE THREAD

**Issue by CindyZhan19891207** [networkupstools/nut#1142]
Hello NUT developers:

After my test, I confirm that TWINPRO3/TWINRT3 UPS are able to support NUT. The issue is Salicru's VID is not supported.
Please help to add Salicru VID (0x2E66) and add this model in compatibility list.   

**Here's the information:
VID/PID: 0x2E66/0X0201
Product Name: TWINPRO3/TWINRT3
Manufacture: Salicru
Type: UPS**

As currently Salicru VID is not supported in NUT, test is performed use VID=0x06DA.
From my test result, upsc, upscmd, upsrw and shutdown sequences are good. 

upsc result:
_root@pc46:~# upsc Unity
Init SSL without certificate database
battery.capacity: 0.00
battery.charge: 91
battery.charge.low: 0
battery.charge.restart: 0
battery.charger.status: floating
battery.protection: yes
battery.runtime: 59940
battery.runtime.low: 180
battery.type: PbAc
device.mfr: PHOENIXTEC
device.model: SLC-1500-TWIN PRO3
device.serial: CP10M3031700001
device.type: ups
driver.name: usbhid-ups
driver.parameter.pollfreq: 30
driver.parameter.pollinterval: 2
driver.parameter.port: auto
driver.parameter.synchronous: no
driver.version: 2.7.4
driver.version.data: MGE HID 1.40
driver.version.internal: 0.41
input.frequency.nominal: 50
input.voltage.nominal: 230
outlet.1.status: on
output.current: 0.00
output.frequency: 50.0
output.frequency.nominal: 50
output.voltage: 230.2
output.voltage.nominal: 230
ups.date: 2019/12/31
ups.delay.shutdown: 20
ups.delay.start: 30
ups.firmware: 00.01.9319
ups.load: 0
ups.mfr: PHOENIXTEC
ups.model: SLC-1500-TWIN PRO3
ups.power: 0
ups.power.nominal: 1500
ups.productid: ffff
ups.realpower: 0
ups.realpower.nominal: 1500
ups.serial: CP10M3031700001
ups.shutdown: enabled
ups.status: OL CHRG
ups.temperature: 25.9
ups.test.interval: 2592000
ups.test.result: Done and passed
ups.time: 20:18:14
ups.timer.shutdown: 0
ups.timer.start: 0
ups.type: online
ups.vendorid: 06da_

upsrw result: 
root@pc46:~# upsc Unity battery.runtime.low
Init SSL without certificate database
180
root@pc46:~# upsrw -s battery.runtime.low Unity
Username (root): root
Password: 
Enter new value for battery.runtime.low: 240
OK
root@pc46:~# upsc Unity battery.runtime.low
Init SSL without certificate database
240

I successfully set the “ups.delay.shutdown” from 20 to 120 via “upsrw -s ups.delay.shutdown Unity” command

upscmd result:
root@pc46:~# upscmd -l Unity
Instant commands supported on UPS [Unity]:

_load.off - Turn off the load immediately
load.off.delay - Turn off the load with a delay (seconds)
load.on - Turn on the load immediately
load.on.delay - Turn on the load with a delay (seconds)
shutdown.return - Turn off the load and return when power is back
shutdown.stayoff - Turn off the load and remain off
shutdown.stop - Stop a shutdown in progress
test.battery.start.deep - Start a deep battery test
test.battery.start.quick - Start a quick battery test
test.battery.stop - Stop the battery test_

Send command “upscmd Unity load.off” , the output voltage has changed from 230.2 to 0 after loading off. 
Send command “upscmd Unity load.on”, the output voltage has changed from 0 to 230.2 after loading on.

**Comment by CindyZhan19891207** [comment]
@jimklimov  Do you need more information?

**Comment by jimklimov** [comment]
Sorry, I thought recent PR #1199 took care of that, adding actual support of Salicru devices - upon revisiting, seems that is for another product line; but at least, that PR defined `SALICRU_VENDORID 0x2e66`

So now I am puzzled what the testing by "VID=0x06DA" meant? Did you reprogram the UPS firmware to report a different VID for the test run?

For clarity, would it be possible for you to build NUT from the current "master" branch on github and test if it would support these models "out of the box" now?

**Comment by CindyZhan19891207** [comment]
@jimklimov  Exactly, when I perform the test in my ticket, I do not notice NUT master version already support Salicru VID.  Test with NUT master again, after modify PID in upsconf, the UPS can successfully establish communication with NUT. So, please help to add PID = 0x0201, 0x0202 and 0x0203 in Salicru product list.

**Comment by CindyZhan19891207** [comment]
@jimklimov  I'd like to have your further inputs. Thanks.

**Comment by CindyZhan19891207** [comment]
@jimklimov  Do you need more information? Let's make it move forward.

**Comment by jimklimov** [comment]
Back from end/start-of-year "vacations" (was pre-occupied with another CI farm migration), and hoping to look at this today - thanks for reminding.

**Comment by jimklimov** [comment]
Just to clarify: in the post from Dec 10, did you re-verify the device with the then-current NUT master branch state, so using the `usbhid-ups` driver and the new `salicru` HID subdriver (not the `mge` one as initially posted)?

Also for posterity (e.g. if someone checks/promotes support for other OEM/branded/... UPSes), it is better not to tweak the UPS firmware to respond to different VID/PID, but to adjust the NUT `ups.conf` file section to explicitly set the subdriver, vendorid and productid triplet of options, e.g.:
````
[myups]
    driver=usbhid_ups
    port=auto
    subdriver=salicru
    vendorid=2e66
    productid=0201
````

This makes the reports more relevant to reproduce later (or for users with older NUT builds deployed/packaged), especially if direct "out of the box" support appears over time.

**Comment by jimklimov** [comment]
Finally figured out how to move ahead on HCL/DDL updates, PRs posted that should close this issue.

**Comment by CindyZhan19891207** [comment]
@jimklimov  Good suggestion, test with out of box is more reasonable. Thanks for your suggestion and support.

**Comment by jimklimov** [comment]
How did it go? Can I merge that PR and close the several issues for Salicru HCL updates, too many years in the making? ;) ;(

**Comment by jimklimov** [comment]
Merged that driver.list and built-in handling for the new VID/PID; feel free to open a new issue (and then reference this one and the PR please) if something still does not fit.
