### ISSUE TITLE
Compile nut v2.7.4 with GCC 11.2.0

### ISSUE THREAD

**Issue by teoberi** [networkupstools/nut#1148]
I already know that it does not compile v2.7.4 with GCC 11.2.0
https://github.com/networkupstools/nut/commit/fab323320d5b955ed034b2eea390a9bbb549e8e5
In Releases for Latest v2.7.4 writes:
`If building NUT from scratch, better take a look at the master branch or one of prospect libusb-1.x support branches. And fingers crossed for a 2.7.5 and beyond soon! ..`
Until the release of v2.7.5 I could try the compilation using the branch:
1. master
2. release-notes-for-2.7.5

**Comment by teoberi** [comment]
I managed to compile, configure and test the master branch (Commits on Nov 2, 2021) with GCC 11.2.0

**Comment by jimklimov** [comment]
Thanks for the confirmation! :)
