### ISSUE TITLE
I aint got no clue

### ISSUE THREAD

**Issue by aplayerv1** [networkupstools/nut#1218]
0.455859     Checking device (0001/0000) (006/003)
   0.467392     - VendorID: 0001
   0.467410     - ProductID: 0000
   0.467415     - Manufacturer: unknown
   0.467420     - Product: MEC0003
   0.467424     - Serial Number: unknown
   0.467428     - Bus: 006
   0.467432     - Device release number: 0100
   0.467435     Trying to match device
   0.467483     Device matches
   0.467510     nut_usb_set_altinterface: skipped usb_set_altinterface(udev, 0)
   0.471336     First supported language ID: 0x409 (please report to the NUT maintainer!)
   0.471360     Trying megatec protocol...
   0.471368     send: Q1
   0.488399     received 96 (96)
   0.488422     read: (000.0 000.0 000.0 000 00.0 0.00 00.0 00000000
   0.488469     Status read in 1 tries
   0.488480     Supported UPS detected with megatec protocol
   0.488486     send: F
   0.498344     received 46 (46)
   0.498361     read: #000.0 0.0 00.00 00.0
   0.498383     Ratings read in 1 tries
   0.498391     No values provided for battery high/low voltages in ups.conf

   0.498399     Using 'guestimation' (low: 0.000000, high: 0.000000)!
   0.498404     Battery runtime will not be calculated (runtimecal not set)
   0.498415     send: Q1
   0.515369     received 96 (96)
   0.515396     read: (000.0 000.0 000.0 000 00.0 0.00 00.0 00000000
   0.515478     dstate_init: sock /var/run/nut/blazer_usb-ups open on fd 5
   0.515493     send: Q1
   0.531352     received 96 (96)
   0.531379     read: (000.0 000.0 000.0 000 00.0 0.00 00.0 00000000
   2.517563     send: Q1
   2.534359     received 96 (96)
   2.534385     read: (000.0 000.0 000.0 000 00.0 0.00 00.0 00000000
   4.519687     send: Q1
   4.536317     received 96 (96)
   4.536335     read: (000.0 000.0 000.0 000 00.0 0.00 00.0 00000000

**Comment by aplayerv1** [comment]
Init SSL without certificate database
battery.voltage: 0.00
battery.voltage.high: 0.00
battery.voltage.low: 0.00
battery.voltage.nominal: 0.0
device.mfr:
device.model:
device.type: ups
driver.name: blazer_usb
driver.parameter.pollinterval: 2
driver.parameter.port: auto
driver.parameter.product: MEC0003
driver.parameter.productid: 0000
driver.parameter.synchronous: no
driver.parameter.vendorid: 0001
driver.version: 2.7.4
driver.version.internal: 0.12
input.current.nominal: 0.0
input.frequency: 0.0
input.frequency.nominal: 0
input.voltage: 0.0
input.voltage.fault: 0.0
input.voltage.nominal: 0
output.voltage: 0.0
ups.beeper.status: disabled
ups.delay.shutdown: 30
ups.delay.start: 180
ups.firmware:
ups.load: 0
ups.mfr:
ups.model:
ups.productid: 0000
ups.status: OL
ups.temperature: 0.0
ups.type: online
ups.vendorid: 0001

**Comment by jimklimov** [comment]
Seems like a report about an unspecified USB device not compatible with your version of NUT (probably the 2.7.4 release, which alas is old now, 2.7.5 is still brewing). Please check if a build from the master branch on github happens to support if better?

**Comment by aplayerv1** [comment]
build from master

Network UPS Tools - Generic Q* USB/Serial driver 0.30 (2.7.4-3652-g5ab91d2d)
USB communication driver 0.33
   0.000000     [D5] send_to_all: SETINFO driver.parameter.port "auto"
   0.000042     [D1] debug level is '5'
   0.001585     [D5] send_to_all: SETINFO device.type "ups"
   0.001603     [D1] upsdrv_initups...
   0.182633     [D3] usb_busses=0x558313127e70
   0.182659     [D2] Checking device (1D6B/0001) (008/001)
   0.210462     [D2] - VendorID: 1d6b
   0.210486     [D2] - ProductID: 0001
   0.210503     [D2] - Manufacturer: Linux 5.4.106-1-pve uhci_hcd
   0.210517     [D2] - Product: UHCI Host Controller
   0.210525     [D2] - Serial Number: 0000:00:1d.2
   0.210532     [D2] - Bus: 008
   0.210541     [D2] - Device: 001
   0.210549     [D2] - Device release number: 0504
   0.210558     [D2] Trying to match device
   0.210566     [D3] match_function_regex: matching a device...
   0.210575     [D2] Device does not match - skipping
   0.210635     [D2] Checking device (1D6B/0001) (007/001)
   0.242357     [D2] - VendorID: 1d6b
   0.242383     [D2] - ProductID: 0001
   0.242388     [D2] - Manufacturer: Linux 5.4.106-1-pve uhci_hcd
   0.242393     [D2] - Product: UHCI Host Controller
   0.242400     [D2] - Serial Number: 0000:00:1d.1
   0.242405     [D2] - Bus: 007
   0.242409     [D2] - Device: 001
   0.242414     [D2] - Device release number: 0504
   0.242422     [D2] Trying to match device
   0.242428     [D3] match_function_regex: matching a device...
   0.242438     [D2] Device does not match - skipping
   0.242498     [D2] Checking device (0001/0000) (006/004)
   0.246275     [D2] - VendorID: 0001
   0.246289     [D2] - ProductID: 0000
   0.246295     [D2] - Manufacturer: unknown
   0.246299     [D2] - Product: unknown
   0.246302     [D2] - Serial Number: unknown
   0.246305     [D2] - Bus: 006
   0.246309     [D2] - Device: 004
   0.246312     [D2] - Device release number: 0100
   0.246315     [D2] Trying to match device
   0.246319     [D3] match_function_regex: matching a device...
   0.246323     [D2] Device matches
   0.246345     [D3] nut_usb_set_altinterface: skipped usb_set_altinterface(udev, 0)
   0.246371     [D5] send_to_all: SETINFO ups.vendorid "0001"
   0.246378     [D5] send_to_all: SETINFO ups.productid "0000"
   0.246395     [D3] send: QGS
   0.246400     [D3] read: QGS
   0.246416     [D2] qx_process_answer: short reply (input.voltage)
   0.246426     [D3] send: QGS
   0.246438     [D3] read: QGS
   0.246458     [D2] qx_process_answer: short reply (input.voltage)
   0.246470     [D3] send: QGS
   0.246481     [D3] read: QGS
   0.246491     [D2] qx_process_answer: short reply (input.voltage)
   0.246500     [D3] send: M
   0.246509     [D3] read: M
   0.246522     [D2] voltronic_qs_protocol: invalid protocol [M]
   0.246534     [D4] ups_infoval_set: failed to preprocess value [ups.firmware.aux: M]
   0.246550     [D3] send: M
   0.246561     [D3] read: M
   0.246579     [D2] voltronic_qs_protocol: invalid protocol [M]
   0.246593     [D4] ups_infoval_set: failed to preprocess value [ups.firmware.aux: M]
   0.246607     [D3] send: M
   0.246615     [D3] read: M
   0.246621     [D2] voltronic_qs_protocol: invalid protocol [M]
   0.246630     [D4] ups_infoval_set: failed to preprocess value [ups.firmware.aux: M]
   0.246640     [D3] send: M
   0.246649     [D3] read: M
   0.246659     [D2] voltronic_qs_hex_protocol: invalid protocol [M]
   0.246668     [D4] ups_infoval_set: failed to preprocess value [ups.firmware.aux: M]
   0.246679     [D3] send: M
   0.246688     [D3] read: M
   0.246698     [D2] voltronic_qs_hex_protocol: invalid protocol [M]
   0.246708     [D4] ups_infoval_set: failed to preprocess value [ups.firmware.aux: M]
   0.246718     [D3] send: M
   0.246727     [D3] read: M
   0.246737     [D2] voltronic_qs_hex_protocol: invalid protocol [M]
   0.246745     [D4] ups_infoval_set: failed to preprocess value [ups.firmware.aux: M]
   0.246756     [D3] send: QS
   0.246764     [D3] read: QS
   0.246770     [D2] qx_process_answer: short reply (input.voltage)
   0.246776     [D3] send: QS
   0.246781     [D3] read: QS
   0.246787     [D2] qx_process_answer: short reply (input.voltage)
   0.246792     [D3] send: QS
   0.246798     [D3] read: QS
   0.246803     [D2] qx_process_answer: short reply (input.voltage)
   0.246809     [D3] send: D
   0.246814     [D3] read: D
   0.246820     [D2] qx_process_answer: short reply (input.voltage)
   0.246826     [D3] send: D
   0.246831     [D3] read: D
   0.246836     [D2] qx_process_answer: short reply (input.voltage)
   0.246842     [D3] send: D
   0.246847     [D3] read: D
   0.246853     [D2] qx_process_answer: short reply (input.voltage)
   0.246859     [D3] send: Q1
   0.250248     [D3] read: error sending control message: Protocol error (-71)
   0.250266     [D4] qx_process: failed to preprocess answer [input.voltage]
   0.250279     [D3] send: Q1
   0.254266     [D3] read: error sending control message: Protocol error (-71)
   0.254286     [D4] qx_process: failed to preprocess answer [input.voltage]
   0.254295     [D3] send: Q1
   0.258250     [D3] read: error sending control message: Protocol error (-71)
   0.258278     [D4] qx_process: failed to preprocess answer [input.voltage]
   0.258295     [D3] send: Q1
   0.262251     [D3] read: error sending control message: Protocol error (-71)
   0.262282     [D4] qx_process: failed to preprocess answer [input.voltage]
   0.262310     [D3] send: Q1
   0.266239     [D3] read: error sending control message: Protocol error (-71)
   0.266258     [D4] qx_process: failed to preprocess answer [input.voltage]
   0.266267     [D3] send: Q1
   0.270210     [D3] read: error sending control message: Protocol error (-71)
   0.270224     [D4] qx_process: failed to preprocess answer [input.voltage]
   0.270240     [D3] send: Q1
   0.274245     [D3] read: error sending control message: Protocol error (-71)
   0.274255     [D4] qx_process: failed to preprocess answer [input.voltage]
   0.274262     [D3] send: Q1
   0.278217     [D3] read: error sending control message: Protocol error (-71)
   0.278230     [D4] qx_process: failed to preprocess answer [input.voltage]
   0.278238     [D3] send: Q1
   0.282234     [D3] read: error sending control message: Protocol error (-71)
   0.282248     [D4] qx_process: failed to preprocess answer [input.voltage]
   0.282261     [D3] send: Q1
   0.286235     [D3] read: error sending control message: Protocol error (-71)
   0.286254     [D4] qx_process: failed to preprocess answer [input.voltage]
   0.286275     [D3] send: Q1
   0.290259     [D3] read: error sending control message: Protocol error (-71)
   0.290274     [D4] qx_process: failed to preprocess answer [input.voltage]
   0.290288     [D3] send: Q1
   0.294266     [D3] read: error sending control message: Protocol error (-71)
   0.294284     [D4] qx_process: failed to preprocess answer [input.voltage]
   0.294304     [D3] send: WH
   0.294313     [D3] read: WH
   0.294318     [D2] qx_process_answer: short reply (series)
   0.294324     [D2] claim: cannot process series
   0.294330     [D3] send: WH
   0.294336     [D3] read: WH
   0.294343     [D2] qx_process_answer: short reply (series)
   0.294347     [D2] claim: cannot process series
   0.294354     [D3] send: WH
   0.294359     [D3] read: WH
   0.294365     [D2] qx_process_answer: short reply (series)
   0.294371     [D2] claim: cannot process series
   0.294377     [D3] send: Q1
   0.298218     [D3] read: error sending control message: Protocol error (-71)
   0.298232     [D4] qx_process: failed to preprocess answer [input.voltage]
   0.298238     [D3] send: Q1
   0.302247     [D3] read: error sending control message: Protocol error (-71)
   0.302265     [D4] qx_process: failed to preprocess answer [input.voltage]
   0.302277     [D3] send: Q1
   0.306223     [D3] read: error sending control message: Protocol error (-71)
   0.306236     [D4] qx_process: failed to preprocess answer [input.voltage]
   0.306248     [D3] send: Q1
   0.310219     [D3] read: error sending control message: Protocol error (-71)
   0.310243     [D4] qx_process: failed to preprocess answer [input.voltage]
   0.310261     [D3] send: Q1
   0.314252     [D3] read: error sending control message: Protocol error (-71)
   0.314270     [D4] qx_process: failed to preprocess answer [input.voltage]
   0.314285     [D3] send: Q1
   0.318232     [D3] read: error sending control message: Protocol error (-71)
   0.318255     [D4] qx_process: failed to preprocess answer [input.voltage]
   0.318260     Device not supported!
   0.318263     Device not supported!

**Comment by aplayerv1** [comment]
built the master 

USB communication driver 0.33
   0.000000     [D5] send_to_all: SETINFO driver.parameter.port "auto"
   0.000056     [D5] send_to_all: SETINFO driver.parameter.vendorid "0001"
   0.000065     [D5] send_to_all: SETINFO driver.parameter.productid "0000"
   0.000073     [D5] send_to_all: SETINFO driver.parameter.bus "006"
   0.000093     [D1] debug level is '6'
   0.012867     [D5] send_to_all: SETINFO device.type "ups"
   0.012893     [D1] upsdrv_initups...
   0.186474     [D3] usb_busses=0x56296d47c860
   0.186514     [D2] Checking device (1D6B/0001) (008/001)
   0.214523     [D2] - VendorID: 1d6b
   0.214546     [D2] - ProductID: 0001
   0.214556     [D2] - Manufacturer: Linux 5.4.106-1-pve uhci_hcd
   0.214571     [D2] - Product: UHCI Host Controller
   0.214582     [D2] - Serial Number: 0000:00:1d.2
   0.214591     [D2] - Bus: 008
   0.214598     [D2] - Device: 001
   0.214603     [D2] - Device release number: 0504
   0.214611     [D2] Trying to match device
   0.214619     [D3] match_function_regex: matching a device...
   0.214634     [D2] match_function_regex: failed match of VendorID: 1d6b
   0.214642     [D2] Device does not match - skipping
   0.214705     [D2] Checking device (1D6B/0001) (007/001)
   0.246423     [D2] - VendorID: 1d6b
   0.246443     [D2] - ProductID: 0001
   0.246447     [D2] - Manufacturer: Linux 5.4.106-1-pve uhci_hcd
   0.246450     [D2] - Product: UHCI Host Controller
   0.246453     [D2] - Serial Number: 0000:00:1d.1
   0.246456     [D2] - Bus: 007
   0.246458     [D2] - Device: 001
   0.246461     [D2] - Device release number: 0504
   0.246464     [D2] Trying to match device
   0.246468     [D3] match_function_regex: matching a device...
   0.246474     [D2] match_function_regex: failed match of VendorID: 1d6b
   0.246477     [D2] Device does not match - skipping
   0.246590     [D2] Checking device (0001/0000) (006/003)
   0.258646     [D2] - VendorID: 0001
   0.258667     [D2] - ProductID: 0000
   0.258672     [D2] - Manufacturer: unknown
   0.258675     [D2] - Product: MEC0003
   0.258680     [D2] - Serial Number: unknown
   0.258686     [D2] - Bus: 006
   0.258689     [D2] - Device: 003
   0.258693     [D2] - Device release number: 0100
   0.258696     [D2] Trying to match device
   0.258700     [D3] match_function_regex: matching a device...
   0.258738     [D2] Device matches
   0.258757     [D2] failed to claim USB device: could not claim interface 0: Device or resource busy
   0.259077     [D2] detached kernel driver from USB device...
   0.259110     [D3] nut_usb_set_altinterface: skipped usb_set_altinterface(udev, 0)
   0.259124     [D5] send_to_all: SETINFO ups.vendorid "0001"
   0.259129     [D5] send_to_all: SETINFO ups.productid "0000"
   0.259143     [D3] send: QGS
   0.259153     [D3] read: QGS
   0.259168     [D2] qx_process_answer: short reply (input.voltage)
   0.259176     [D3] send: QGS
   0.259189     [D3] read: QGS
   0.259204     [D2] qx_process_answer: short reply (input.voltage)
   0.259213     [D3] send: QGS
   0.259222     [D3] read: QGS
   0.259229     [D2] qx_process_answer: short reply (input.voltage)
   0.259234     [D3] send: M
   0.259243     [D3] read: M
   0.259252     [D2] voltronic_qs_protocol: invalid protocol [M]
   0.259257     [D4] ups_infoval_set: failed to preprocess value [ups.firmware.aux: M]
   0.259261     [D3] send: M
   0.259265     [D3] read: M
   0.259271     [D2] voltronic_qs_protocol: invalid protocol [M]
   0.259275     [D4] ups_infoval_set: failed to preprocess value [ups.firmware.aux: M]
   0.259281     [D3] send: M
   0.259288     [D3] read: M
   0.259294     [D2] voltronic_qs_protocol: invalid protocol [M]
   0.259301     [D4] ups_infoval_set: failed to preprocess value [ups.firmware.aux: M]
   0.259308     [D3] send: M
   0.259312     [D3] read: M
   0.259323     [D2] voltronic_qs_hex_protocol: invalid protocol [M]
   0.259329     [D4] ups_infoval_set: failed to preprocess value [ups.firmware.aux: M]
   0.259334     [D3] send: M
   0.259340     [D3] read: M
   0.259352     [D2] voltronic_qs_hex_protocol: invalid protocol [M]
   0.259362     [D4] ups_infoval_set: failed to preprocess value [ups.firmware.aux: M]
   0.259373     [D3] send: M
   0.259379     [D3] read: M
   0.259390     [D2] voltronic_qs_hex_protocol: invalid protocol [M]
   0.259395     [D4] ups_infoval_set: failed to preprocess value [ups.firmware.aux: M]
   0.259402     [D3] send: QS
   0.259407     [D3] read: QS
   0.259413     [D2] qx_process_answer: short reply (input.voltage)
   0.259420     [D3] send: QS
   0.259425     [D3] read: QS
   0.259431     [D2] qx_process_answer: short reply (input.voltage)
   0.259436     [D3] send: QS
   0.259440     [D3] read: QS
   0.259445     [D2] qx_process_answer: short reply (input.voltage)
   0.259452     [D3] send: D
   0.259457     [D3] read: D
   0.259464     [D2] qx_process_answer: short reply (input.voltage)
   0.259469     [D3] send: D
   0.259475     [D3] read: D
   0.259481     [D2] qx_process_answer: short reply (input.voltage)
   0.259487     [D3] send: D
   0.259493     [D3] read: D
   0.259498     [D2] qx_process_answer: short reply (input.voltage)
   0.259506     [D3] send: Q1
   0.259513     [D4] command index: 0x03
   0.259519     [D3] asking for: 00
   0.307641     [D5] read: (47 bytes) => 28 30 30 30 2e 30 20 30 30 30 2e 30 20 30 30 30 2e 30
   0.307668     [D5]  20 30 30 30 20 30 30 2e 30 20 30 2e 30 30 20 30 30 2e 30 20 30 30 30 30 30
   0.307675     [D5]  30 30 30 0d
   0.307679     [D3] read: (000.0 000.0 000.0 000 00.0 0.00 00.0 00000000
   0.307697     [D5] send_to_all: SETINFO input.voltage "0.0"
   0.307707     [D3] send: ID
   0.307714     [D3] read: ID
   0.307720     [D4] bestups_preprocess_id_answer: wrong length [device.model: 3]
   0.307727     [D4] qx_process: failed to preprocess answer [device.model]
   0.307734     [D5] send_to_all: DELINFO input.voltage
   0.307741     [D3] send: Q1
   0.307746     [D4] command index: 0x03
   0.307752     [D3] asking for: 0D
   0.339687     [D5] read: (47 bytes) => 28 30 30 30 2e 30 20 30 30 30 2e 30 20 30 30 30 2e 30
   0.339718     [D5]  20 30 30 30 20 30 30 2e 30 20 30 2e 30 30 20 30 30 2e 30 20 30 30 30 30 30
   0.339727     [D5]  30 30 30 0d
   0.339732     [D3] read: (000.0 000.0 000.0 000 00.0 0.00 00.0 00000000
   0.339752     [D5] send_to_all: SETINFO input.voltage "0.0"
   0.339760     [D3] send: ID
   0.339767     [D3] read: ID
   0.339773     [D4] bestups_preprocess_id_answer: wrong length [device.model: 3]
   0.339777     [D4] qx_process: failed to preprocess answer [device.model]
   0.339785     [D5] send_to_all: DELINFO input.voltage
   0.339790     [D3] send: Q1
   0.339795     [D4] command index: 0x03
   0.361695     [D5] read: (47 bytes) => 28 30 30 30 2e 30 20 30 30 30 2e 30 20 30 30 30 2e 30
   0.361726     [D5]  20 30 30 30 20 30 30 2e 30 20 30 2e 30 30 20 30 30 2e 30 20 30 30 30 30 30
   0.361735     [D5]  30 30 30 0d
   0.361742     [D3] read: (000.0 000.0 000.0 000 00.0 0.00 00.0 00000000
   0.361760     [D5] send_to_all: SETINFO input.voltage "0.0"
   0.361770     [D3] send: ID
   0.361778     [D3] read: ID
   0.361784     [D4] bestups_preprocess_id_answer: wrong length [device.model: 3]
   0.361790     [D4] qx_process: failed to preprocess answer [device.model]
   0.361796     [D5] send_to_all: DELINFO input.voltage
   0.361800     [D3] send: Q1
   0.361806     [D4] command index: 0x03
   0.361812     [D3] asking for: 0C
   0.398701     [D5] read: (47 bytes) => 28 30 30 30 2e 30 20 30 30 30 2e 30 20 30 30 30 2e 30
   0.398727     [D5]  20 30 30 30 20 30 30 2e 30 20 30 2e 30 30 20 30 30 2e 30 20 30 30 30 30 30
   0.398736     [D5]  30 30 30 0d
   0.398743     [D3] read: (000.0 000.0 000.0 000 00.0 0.00 00.0 00000000
   0.398759     [D5] send_to_all: SETINFO input.voltage "0.0"
   0.398772     [D3] send: QPI
   0.398780     [D3] read: QPI
   0.398785     [D2] qx_process_answer: short reply (ups.firmware.aux)
   0.398790     [D5] send_to_all: DELINFO input.voltage
   0.398796     [D3] send: Q1
   0.398802     [D4] command index: 0x03
   0.398808     [D3] asking for: 0D
   1.443668     [D3] read: error sending control message: Connection timed out (-110)
   1.443693     [D4] qx_process: failed to preprocess answer [input.voltage]
   1.443704     [D3] send: Q1
   1.443710     [D4] command index: 0x03
   2.402659     [D3] read: error sending control message: Invalid or incomplete multibyte or wide character (-84)
   2.402686     [D4] qx_process: failed to preprocess answer [input.voltage]
   2.402699     [D3] send: Q1
   2.402705     [D4] command index: 0x03
   2.402711     [D3] asking for: 0C
   2.410665     [D3] read: error sending control message: Protocol error (-71)
   2.410700     [D4] qx_process: failed to preprocess answer [input.voltage]
   2.410713     [D3] send: Q1
   2.410721     [D4] command index: 0x03
   2.410734     [D3] asking for: 0D
   2.418621     [D3] read: error sending control message: Protocol error (-71)
   2.418646     [D4] qx_process: failed to preprocess answer [input.voltage]
   2.418659     [D3] send: Q1
   2.418668     [D4] command index: 0x03
   2.422609     [D3] read: error sending control message: Protocol error (-71)
   2.422620     [D4] qx_process: failed to preprocess answer [input.voltage]
   2.422626     [D3] send: Q1
   2.422629     [D4] command index: 0x03
   2.422633     [D3] asking for: 0C
   2.430631     [D3] read: error sending control message: Protocol error (-71)
   2.430652     [D4] qx_process: failed to preprocess answer [input.voltage]
   2.430667     [D3] send: Q1
   2.430675     [D4] command index: 0x03
   2.430680     [D3] asking for: 0D
   2.438653     [D3] read: error sending control message: Protocol error (-71)
   2.438671     [D4] qx_process: failed to preprocess answer [input.voltage]
   2.438680     [D3] send: Q1
   2.438686     [D4] command index: 0x03
   2.442672     [D3] read: error sending control message: Protocol error (-71)
   2.442693     [D4] qx_process: failed to preprocess answer [input.voltage]
   2.442712     [D3] send: WH
   2.442726     [D3] read: WH
   2.442736     [D2] qx_process_answer: short reply (series)
   2.442744     [D2] claim: cannot process series
   2.442757     [D3] send: WH
   2.442766     [D3] read: WH
   2.442775     [D2] qx_process_answer: short reply (series)
   2.442781     [D2] claim: cannot process series
   2.442788     [D3] send: WH
   2.442796     [D3] read: WH
   2.442803     [D2] qx_process_answer: short reply (series)
   2.442809     [D2] claim: cannot process series
   2.442818     [D3] send: Q1
   2.442826     [D4] command index: 0x03
   2.442834     [D3] asking for: 0C
   2.450624     [D3] read: error sending control message: Protocol error (-71)
   2.450643     [D4] qx_process: failed to preprocess answer [input.voltage]
   2.450656     [D3] send: Q1
   2.450665     [D4] command index: 0x03
   2.450673     [D3] asking for: 0D
   2.458618     [D3] read: error sending control message: Protocol error (-71)
   2.458639     [D4] qx_process: failed to preprocess answer [input.voltage]
   2.458649     [D3] send: Q1
   2.458657     [D4] command index: 0x03
   2.462612     [D3] read: error sending control message: Protocol error (-71)
   2.462626     [D4] qx_process: failed to preprocess answer [input.voltage]
   2.462634     [D3] send: Q1
   2.462639     [D4] command index: 0x03
   2.462643     [D3] asking for: 0C
   2.470647     [D3] read: error sending control message: Protocol error (-71)
   2.470667     [D4] qx_process: failed to preprocess answer [input.voltage]
   2.470676     [D3] send: Q1
   2.470681     [D4] command index: 0x03
   2.470686     [D3] asking for: 0D
   2.478651     [D3] read: error sending control message: Protocol error (-71)
   2.478673     [D4] qx_process: failed to preprocess answer [input.voltage]
   2.478686     [D3] send: Q1
   2.478693     [D4] command index: 0x03
   2.482669     [D3] read: error sending control message: Protocol error (-71)
   2.482686     [D4] qx_process: failed to preprocess answer [input.voltage]
   2.482695     Device not supported!
   2.482701     Device not supported!

**Comment by jimklimov** [comment]
Looking by device ID, seems people did succeed recently, as logged in #537
- please check if some suggestions there help?
