### ISSUE TITLE
Njoy (aten pro 3000 va)

### ISSUE THREAD

**Issue by Shiroe93** [networkupstools/nut#1281]
I've noticed that there is absolutely no support for the brand Njoy there is a specific reason why you don't support this ups brand? In my specific case I have an aten pro 3000 va

**Comment by jimklimov** [comment]
Probably because nobody coded and contributed a driver for that? And/or did not report that an existing driver works for those models and brands (quite possible since there are relatively few OEMs whose devices and/or protocols are resold by many vendors).

**Comment by jimklimov** [comment]
According to #867, at least one nJoy is known working.

**Comment by Shiroe93** [comment]
I've managed to get it working partially with an snmp card and the snmp-ups driver unfortunately though I was not able to see temps ![Screenshot_20220410-172545639 (1).jpg](https://user-images.githubusercontent.com/56954468/162626880-789c9d72-4b88-4d40-9c5c-631d58ba358b.jpg)
This is the data i was able to pull in my home assistant instance

**Comment by jimklimov** [comment]
@Shiroe93 : Did you have a chance to check with some `snmpwalk` or similar tool, and an NJoy vendor extensions MIB if they publish one, whether it *can* report the temperatures etc.?

The default IETF MIB mapping only has a `battery.temperature` data point...

**Comment by Shiroe93** [comment]
At the moment I bought the lan add on card and I'm using that to retrieve the data via snmtp protocol

**Comment by jimklimov** [comment]
Thanks. I mean this part of your most-recent post:

> I've managed to get it working partially with an snmp card and the snmp-ups driver unfortunately though I was not able to see temps 

Are you monitoring with NUT now or directly with some other SNMP client?
If you tried other SNMP clients - did you find a way to display temps there? (It may be in a non-standard OID sub-tree as defined by vendor extension).

**Comment by Shiroe93** [comment]
I'm using the nut add on in home assistant
