### ISSUE TITLE
I need help! I have some problems...

### ISSUE THREAD

**Issue by Itay1787** [networkupstools/nut#1340]
Hello everyone,
There are some things I did not really understand that I would love for you to help me with.
I want the option to completely disable FSD I do not want nut to put my UPSs in FSD mode.
And on top of that - what exactly is FSD? I understand he's just sending a command to turn off the nut server right? Does this cause the ups to turn off after that in this mode or the battery to run out one way or another faster than in normal ONBATT mode?

I send all the shutdown commands and do everything through my script, I do not want nut to do any shutdown itself. I use it that it will just be a connection between the ups and my script.

My configuration
I have two nut servers that each have their own UPS connected (they are in different places so I can't connect them to the same one).
That one of them is the main one and that's where the script is and it runs and does everything and the other one just passes the information from the UPS to the main nut server.

And one more thing
I do not know if it's a problem with the nut or with my ups or my power is crazy. But I see (because I set that I get emails) that from time to time one of the ups - the one that is connected to the secondary server goes to ONBATT mode and then immediately returns to ONLINE in about 15 seconds maybe a little more. And I don't understand why he does that. I would be happy if you could help me with that as well.

In addition to that the same UPS that is connected to the secondary server from time to time - the driver seems to lose itself and I get this error `Error: Data stale`
From what I read it's something with the `pollfreq` but I keep changing it upwards, and it does not work and also 30 seconds is a lot of time if there is a power outage. If it can not be solved and it must be 30 seconds (if it really is the cause of the problem - I'm still checking it) then ok, but if you have a solution for that I will thank you very much.

**UPS models**
Connected to the main server - Advice Power Vision PV650
Connected to the secondary server - Advice PRD 750

**Configs from the main nut server**

ups.conf
```
pollinterval = 1
maxretry = 3

[network-ups]
     driver = "blazer_usb"
     port = "auto"
     vendorid = "0665"
     productid = "5161"
     product = "USB to Serial"
     vendor = "INNO TECH"
 ```
upsmon.conf
```
RUN_AS_USER root

MONITOR network-ups@localhost 1 user pass master
MONITOR servers-ups@192.168.1.78 1 user pass slave

NOTIFYFLAG ONLINE EXEC
NOTIFYFLAG ONBATT EXEC
NOTIFYFLAG LOWBATT EXEC
NOTIFYFLAG COMMBAD EXEC
NOTIFYFLAG NOCOMM EXEC
NOTIFYFLAG COMMOK EXEC

NOTIFYCMD /etc/nut/scripts/whattodo-upss.sh
```
**Configs from the second server**

ups.conf 
```
pollinterval = 1
maxretry = 3

[servers-ups]
    driver = "usbhid-ups"
    port = "auto"
    vendorid = "0D9F"
    productid = "0004"
    product = "HID UPS Battery"
    serial = "serial123"
    vendor = "POWERCOM Co.,LTD"
    pollfreq = "30"
```
upsd.conf 
```
MAXAGE 25
LISTEN 0.0.0.0 3493
```
upsmon.conf
```
RUN_AS_USER root

MONITOR servers-ups@localhost 1 user pass master
```

**Comment by jimklimov** [comment]
"FSD" stands for "Forced Shut Down" which is a state that `upsmon` in primary (master) mode sets when power goes critical (not enough power sources fed reliably) and tells all secondaries (slaves) and later itself to shut down. This is loosely related with use of `POWERDOWNFLAG` file that can be touched on the server of the primary `upsmon` in such case, and if such file exists when the shutdown scripts are processed - this machine tries to tell the UPSes connected to it to power down (hoping they come back up after wall power is cycled, or after some downtime).

This can probably be avoided by running all `upsmon` instances in secondary mode.
