### ISSUE TITLE
blazer_usb not running [FreeBSD 8.4 "Unknown error" when scanning USB]

### ISSUE THREAD

**Issue by kiim11** [networkupstools/nut#137]
I have USB UPS 1500VA Ippon < Innova RT 1, 5K
# usbconfig -u 0 -a 3 dump_device_desc

ugen0.3: <USB UPS PPC> at usbus0, cfg=0 md=HOST spd=LOW (1.5Mbps) pwr=ON

  bLength = 0x0012
  bDescriptorType = 0x0001
  bcdUSB = 0x0200
  bDeviceClass = 0x0000
  bDeviceSubClass = 0x0000
  bDeviceProtocol = 0x0000
  bMaxPacketSize0 = 0x0008
  idVendor = 0x06da
  idProduct = 0x0005
  bcdDevice = 0x0003
  iManufacturer = 0x0003  <PPC>
  iProduct = 0x0001  <USB UPS>
  iSerialNumber = 0x0000  <no string>
  bNumConfigurations = 0x0001

My ups.conf is 
[ipponUsb0]
vendorid = 06DA
productid = 0005
port = /dev/ugen0.3
driver = blazer_usb

When i run driver it tells

./bin/blazer_usb -a ipponUsb0 -DDD
Network UPS Tools - Megatec/Q1 protocol USB driver 0.11 (2.7.2)
   0.000000 debug level is '3'
   0.008811 Checking device (06DA/0005) (/dev/usb//dev/ugen0.3)
   0.008844 Failed to open device, skipping. (Unknown error)
   0.008849 Checking device (0835/1601) (/dev/usb//dev/ugen1.3)
   0.008869 Failed to open device, skipping. (Unknown error)
   0.008873 Checking device (8087/0024) (/dev/usb//dev/ugen1.2)
   0.008892 Failed to open device, skipping. (Unknown error)
   0.008896 Checking device (8087/0024) (/dev/usb//dev/ugen0.2)
   0.008914 Failed to open device, skipping. (Unknown error)
   0.008919 Checking device (0000/0000) (/dev/usb//dev/ugen1.1)
   0.008936 Failed to open device, skipping. (Unknown error)
   0.008940 Checking device (0000/0000) (/dev/usb//dev/ugen0.1)
   0.008957 Failed to open device, skipping. (Unknown error)
   0.008962 No appropriate HID device found
   0.008967 No supported devices found. Please check your device availability with 'lsusb'
and make sure you have an up-to-date version of NUT. If this does not help,
try running the driver with at least 'subdriver', 'vendorid' and 'productid'
options specified. Please refer to the man page for details about these options
(man 8 blazer_usb).

**Comment by clepple** [comment]
The [EoL date for FreeBSD 8.4 was 2015-08-01](https://www.freebsd.org/security/unsupported.html). This is probably the same underlying issue as #490.
