### ISSUE TITLE
USB permission issues related to Linux / udev

### ISSUE THREAD

**Issue by aquette** [networkupstools/nut#140]
udev rules are applied too late (priority 52), resulting in nut privileges being overwritten.
The final result is that the driver doesn't start, and connection failure to the driver / UPS are reported by upsd and upsmon.

The fix is simply to set priority to 62 by renaming the rules file:
$ mv /lib/udev/rules.d/{5,6}2-nut-usbups.rules

This bug affects:
- Debian: http://bugs.debian.org/721600
- Fedora / Redhat: https://bugzilla.redhat.com/show_bug.cgi?id=488368
- Ubuntu: https://bugs.launchpad.net/debian/+source/nut/+bug/1099947
  and probably all Linux distribution

**Comment by clepple** [comment]
If you still need to unplug/replug the USB cable on Ubuntu, it may be related to this bug: https://bugs.launchpad.net/ubuntu/+source/nut/+bug/1540008
