### ISSUE TITLE
[HCL] <Cyber Power Systems> <CPJ500> supported by <usbhid-ups>

### ISSUE THREAD

**Issue by ChanningHe** [networkupstools/nut#1403]
link to the manufacturer’s online description of the device: https://www.cyberpower.com/jp/ja/product/sku/cpj500#downloads

**Comment by ChanningHe** [comment]
Here is upsc output

Init SSL without certificate database
battery.charge: 100
battery.charge.low: 10
battery.charge.warning: 20
battery.mfr.date: CPS
battery.runtime: 2250
battery.runtime.low: 300
battery.type: PbAcid
battery.voltage: 13.5
battery.voltage.nominal: 12
device.mfr: CPS
device.model: CPJ500
device.type: ups
driver.name: usbhid-ups
driver.parameter.pollfreq: 30
driver.parameter.pollinterval: 15
driver.parameter.port: auto
driver.parameter.synchronous: no
driver.version: 2.7.4
driver.version.data: CyberPower HID 0.4
driver.version.internal: 0.41
input.transfer.high: 123
input.transfer.low: 82
input.voltage: 101.0
input.voltage.nominal: 228
output.voltage: 101.0
ups.beeper.status: enabled
ups.delay.shutdown: 20
ups.delay.start: 30
ups.load: 24
ups.mfr: CPS
ups.model: CPJ500
ups.productid: 0501
ups.realpower.nominal: 300
ups.status: OL
ups.test.result: No test initiated
ups.timer.shutdown: -60
ups.timer.start: -60
ups.vendorid: 0764

**Comment by jimklimov** [comment]
Thanks!
