### ISSUE TITLE
Missing signature for 2.8.0 release

### ISSUE THREAD

**Issue by atsampson** [networkupstools/nut#1410]
NUT tarball releases usually have a GPG signature so packagers can verify they're legitimate.

However, the 2.8.0 release doesn't seem to have one - the link on [the download page](https://networkupstools.org/download.html) is broken, and there's no file in the [download directory](https://networkupstools.org/source/2.8/).

**Comment by atsampson** [comment]
Great - thanks, Jim!

**Comment by jimklimov** [comment]
So... it took a while to get feet wet, but now I have a GPG key pushed out to some registries like openpgp, debian and ubuntu. Wondering what the next part is, if some distros or their keychains should include me in packages? :)

**Comment by jimklimov** [comment]
FWIW, my fancy new GPG key ID is below:
````
$ gpg --recv-key DE0184DA7043DCF7
gpg: key DE0184DA7043DCF7: public key "Jim Klimov (Doing FOSS since last millennium) <jimklimov@gmail.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
````

**Comment by jimklimov** [comment]
Tagged https://github.com/networkupstools/nut/releases/tag/v2.8.0-signed and posted the signature file (nut-website "source" repo and github release attachment).

**Comment by jimklimov** [comment]
https://github.com/networkupstools/networkupstools.github.io/commit/dc3665a961e8df47db2315b004bee057f1642665

**Comment by jimklimov** [comment]
SIG file finally got made and published, this issue is resolved :)

(There is another related issue of Download page offering a non-release tag currently; however it is possible to get through the "You can also browse the [stable source directory](http://www.networkupstools.org/source/2.8/)" link for verification).
