### ISSUE TITLE
nut 2.8.0 build failure on MacOS

### ISSUE THREAD

**Issue by chenrui333** [networkupstools/nut#1415]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>build error</summary>

```
dummy-ups.c:238:24: error: no member named 'st_mtim' in 'struct stat'
                                        if (datafile_stat.st_mtim.tv_sec != fs.st_mtim.tv_sec) {
                                            ~~~~~~~~~~~~~ ^
dummy-ups.c:238:45: error: no member named 'st_mtim' in 'struct stat'
                                        if (datafile_stat.st_mtim.tv_sec != fs.st_mtim.tv_sec) {
                                                                            ~~ ^
2 errors generated.
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/2287073413
relates to Homebrew/homebrew-core#101035

**Comment by jimklimov** [comment]
That would be MacOS? Which version? Hope I can find some clues in public
headers. Maintaining compat with obscure proprietary systems is hard
guesswork :\

Aldernately, can you locate and experiment how tge file modification time
field is called in `struct stat`, if present?

**Comment by jimklimov** [comment]
Thanks for the nudge, I managed to get a MacOS build environment (on CircleCI) willing to build NUT, so iterated some more attempts to see and fix (or quickly hide) some more platform-specific issues which issued warnings and CI is set to treat those as fatal. Will post a PR soon-ish when that job finally passes :)

**Comment by chenrui333** [comment]
Thanks @jimklimov！
