### ISSUE TITLE
"Can't open /etc/nut/upssched.conf: Permission denied"

### ISSUE THREAD

**Issue by drbogar** [networkupstools/nut#1435]
uname -a: `Linux nut-test 5.10.0-14-amd64 #1 SMP Debian 5.10.113-1 (2022-04-29) x86_64 GNU/Linux`

When I generate an event, the following error appears in the service log:
```
máj 31 10:14:01 nut-test upssched[1386]: Can't open /etc/nut/upssched.conf: Permission denied
```

The permissions of the upssched.conf file:
```
-rw-r----- 1 root nut 464 máj   18 12.14 upssched.conf
```

The upsmon runs as the nut user, and the nut user is a member of the nut group.

What am I missing?

**Comment by biergaizi** [comment]
I'm not the project maintainer. But let start from the basics: What is the permission of `/etc/nut` itself? A user or group needs `x` privilege in order to open a directory.

**Comment by biergaizi** [comment]
Glad I could help.
