### ISSUE TITLE
Mecer ME-1000-WTU supported by blazer_usb

### ISSUE THREAD

**Issue by sliverc** [networkupstools/nut#148]
I have successfully tested the Mecer ME-1000-WTU - nut recognized when the UPS is on battery and also when the battery is low whereas a shutdown signal is sent.

> Aug 21 09:38:57 NI-1 upsmon[2959]: UPS Mecer-NI@localhost on battery
Aug 21 09:39:07 NI-1 upsmon[2959]: UPS Mecer-NI@localhost on line power

Specification (last page):
http://www.comx-computers.co.za/download/mecer/ME-1000-WTU.pdf

upsc:
> battery.voltage: 41.04
battery.voltage.nominal: 36.0
beeper.status: enabled
device.mfr:
device.model: HV 1K
device.type: ups
driver.name: blazer_usb
driver.parameter.pollinterval: 2
driver.parameter.port: auto
driver.version: 2.6.3
driver.version.internal: 0.04
input.current.nominal: 4.0
input.frequency: 50.0
input.frequency.nominal: 50
input.voltage: 241.1
input.voltage.fault: 241.1
input.voltage.nominal: 230
output.voltage: 241.2
ups.delay.shutdown: 30
ups.delay.start: 180
ups.firmware: 00443.08
ups.load: 9
ups.mfr:
ups.model: HV 1K
ups.productid: 5161
ups.status: OL BYPASS
ups.temperature: 25.4
ups.type: online
ups.vendorid: 0665

upscmd:
> Instant commands supported on UPS [Mecer-NI]:
beeper.toggle - Toggle the UPS beeper
load.off - Turn off the load immediately
load.on - Turn on the load immediately
shutdown.return - Turn off the load and return when power is back
shutdown.stayoff - Turn off the load and remain off
shutdown.stop - Stop a shutdown in progress
test.battery.start - Start a battery test
test.battery.start.deep - Start a deep battery test
test.battery.start.quick - Start a quick battery test
test.battery.stop - Stop the battery test

I have not been able to change any settings though due to missing credentials:
> Unexpected response from upsd: ERR ACCESS-DENIED

/lib/nut/blazer_usb -a Mecer-NI -DDDD:
> Network UPS Tools - Megatec/Q1 protocol USB driver 0.04 (2.6.3)
   0.000000	debug level is '4'
   0.329687	Checking device (1D6B/0001) (006/001)
   0.393496	- VendorID: 1d6b
   0.393543	- ProductID: 0001
   0.393554	- Manufacturer: unknown
   0.393565	- Product: unknown
   0.393575	- Serial Number: unknown
   0.393585	- Bus: 006
   0.393595	Trying to match device
   0.393615	Device does not match - skipping
   0.393669	Checking device (0665/5161) (005/002)
   0.393720	- VendorID: 0665
   0.393732	- ProductID: 5161
   0.393742	- Manufacturer: unknown
   0.393753	- Product: unknown
   0.393763	- Serial Number: unknown
   0.393774	- Bus: 005
   0.393783	Trying to match device
   0.393796	Device matches
   0.393816	failed to claim USB device: could not claim interface 0: Device or resource busy
   0.393865	detached kernel driver from USB device...
   0.395844	Trying megatec protocol...
   0.398775	send: Q1
   0.635814	read: 40.7 240.7 010 50.0 2.28 25.6 00100001
   0.635925	blazer_status: short reply
   0.635966	Status read 1 failed
   0.638689	send: Q1
   0.875808	read: (240.8 240.8 240.8 008 50.0 2.28 25.6 00100001
   0.876373	Status read in 2 tries
   0.876521	Supported UPS detected with megatec protocol
   0.878718	send: F
   0.995736	read: #230.0 004 036.0 50.0
   0.996020	Ratings read in 1 tries
   0.998673	send: I
   1.187818	read: #                HV 1K      00443.08  
   1.187892	Vendor information read in 1 tries
   1.187906	Battery runtime will not be calculated (runtimecal not set)
   1.190672	send: Q1
   1.427791	read: (240.8 240.7 240.7 009 50.0 2.28 25.6 00100001
   1.428040	dstate_init: sock /var/run/nut/blazer_usb-Mecer-NI open on fd 6
   1.430713	send: Q1
   1.683792	read: (240.7 240.7 240.7 009 50.0 2.28 25.6 00100001
   3.229824	new connection on fd 7
   3.430802	send: Q1
   3.683723	read: (240.6 240.4 240.5 008 50.0 2.27 25.4 00100001
   5.432803	send: Q1
   5.667796	read: (240.1 240.1 240.0 010 50.0 2.28 25.6 00100001
   7.433732	send: Q1
   7.667734	read: (240.2 240.1 240.0 009 50.0 2.28 25.6 00100001
   9.434725	send: Q1
   9.694833	read: (240.4 240.2 240.1 010 50.0 2.28 25.6 00100001
  11.436715	send: Q1
  11.683657	read: (240.5 240.5 240.5 010 50.0 2.28 25.6 00100001
  13.438710	send: Q1
  13.683735	read: (240.6 240.5 240.6 010 50.0 2.28 25.6 00100001
  15.440798	send: Q1
  15.675690	read: (240.3 239.4 240.9 010 50.0 2.28 25.6 00100001
  17.441728	send: Q1
  17.675670	read: (240.0 240.1 240.1 009 50.0 2.28 25.6 00100001
  19.442726	send: Q1
  19.675699	read: (240.2 240.2 240.3 009 50.0 2.28 25.6 00100001
  21.443696	send: Q1
  21.675764	read: (240.5 240.4 240.5 010 50.0 2.28 25.6 00100001
  23.445689	send: Q1
  23.683790	read: (240.8 240.6 240.7 008 50.0 2.28 25.6 00100001
  25.446785	send: Q1
  25.683790	read: (240.6 240.6 240.7 010 50.0 2.28 25.6 00100001
  27.448792	send: Q1
  27.683731	read: (240.2 240.2 240.4 010 50.0 2.28 25.6 00100001

**Comment by sliverc** [comment]
Finally got around to test this using version 2.7.1 which was packaged for my distribution.

Test was successful. Also turning off of beeper worked with upscmd.

upsc:
battery.charge: 100
battery.energysave: no
battery.packs: 1
battery.runtime: 15480
battery.voltage: 41.00
battery.voltage.nominal: 36.0
device.model: W1K
device.type: ups
driver.name: nutdrv_qx
driver.parameter.alarm_control: disable
driver.parameter.pollfreq: 30
driver.parameter.pollinterval: 2
driver.parameter.port: auto
driver.version: 2.7.1
driver.version.data: Voltronic 0.01
driver.version.internal: 0.01
input.current.nominal: 4.0
input.frequency: 50.0
input.frequency.nominal: 50.0
input.phases: 1
input.transfer.high: 242
input.transfer.high.max: 254
input.transfer.high.min: 237
input.transfer.low: 218
input.transfer.low.max: 223
input.transfer.low.min: 206
input.voltage: 211.9
input.voltage.nominal: 230.0
output.current: 0.4
output.current.nominal: 4
output.frequency: 50.0
output.frequency.nominal: 50.0
output.phases: 1
output.power.maximum.percent: 11
output.power.minimum.percent: 5
output.powerfactor: 0.8
output.voltage: 229.7
output.voltage.nominal: 230.0
ups.beeper.status: enabled
ups.delay.shutdown: 30
ups.delay.start: 180
ups.firmware: 00443.09
ups.firmware.aux: P01
ups.load: 9
ups.power.nominal: 1000
ups.productid: 5161
ups.start.auto: yes
ups.start.battery: yes
ups.status: OL
ups.temperature: 29.5
ups.type: online
ups.vendorid: 0665

upscmd:
beeper.disable - Disable the UPS beeper
beeper.enable - Enable the UPS beeper
beeper.toggle - Toggle the UPS beeper
bypass.start - Put the UPS in bypass mode
bypass.stop - Take the UPS out of bypass mode
load.off - Turn off the load immediately
load.on - Turn on the load immediately
shutdown.return - Turn off the load and return when power is back
shutdown.stayoff - Turn off the load and remain off
shutdown.stop - Stop a shutdown in progress
test.battery.start - Start a battery test
test.battery.start.deep - Start a deep battery test
test.battery.start.quick - Start a quick battery test
test.battery.stop - Stop the battery test

**Comment by zykh** [comment]
Thanks! - committed to DDL and HCL.
