### ISSUE TITLE
FAQ: "usbfs: process ? (usbhid-ups) did not claim interface 0 before use"

### ISSUE THREAD

**Issue by clepple** [networkupstools/nut#161]
On Linux, if two copies of a driver are competing for the UPS, these messages will appear in dmesg:

    usbfs: process 29641 (usbhid-ups) did not claim interface 0 before use

This can be a symptom of a source install conflicting with a package install.

**Comment by srl295** [comment]
^ should that be `ps aux | grep usbhid-ups`?

**Comment by srl295** [comment]
I'll tell you my cause.  My cause was having `nutdev2` and `nutdev3` share the same serial number.

1. ran `nut-scanner` with only 2 UPSes plugged in. so far so good
2. updated ups.conf
3. plugged in 3rd ups
4. ran `nut-scanner` and _assumed_ i only needed to "add" nutdev3 to the end of ups.conf
5. Reality was that the "third" UPS became nutdev2, and nutdev2 moved to nutdev3 in the scanner's output.

Would be nice if there was code to detect duplicate serial numbers.

**Comment by braiam** [comment]
This seems to also happen on wakeup from suspend:

```
[589159.185906] random: crng reseeded on system resumption
[589159.185979] PM: suspend exit
[589159.186203] snd_hda_codec_hdmi hdaudioC0D0: HDMI: ELD buf size is 0, force 128
[589159.186220] snd_hda_codec_hdmi hdaudioC0D0: HDMI: invalid ELD data byte 0
[589159.186249] snd_hda_codec_hdmi hdaudioC0D0: HDMI: ELD buf size is 0, force 128
[589159.186264] snd_hda_codec_hdmi hdaudioC0D0: HDMI: invalid ELD data byte 0
[589159.186290] usb 3-2: usbfs: process 184666 (usbhid-ups) did not claim interface 0 before use
[589159.196761] hid-generic 0003:0764:0501.0010: hiddev2,hidraw4: USB HID v1.10 Device [CPS CP850PFCLCD] on usb-0000:08:00.0-2/input0```

**Comment by jimklimov** [comment]
@srl295 : since this week, nut-scanner should generate more matching fields into config, including "bus" and "device" (port) number which most USB-aware drivers consult when searching for supported unique devices.

Good point about warning for bogus (all-zero) or duplicate serials though.

**Comment by jimklimov** [comment]
@braiam : I think there was a discussion about suspend/resume support, either here in issues or on mailing list, sometime last year.

I suppose what happened here was that as part of that kernel took away the device to put it to sleep. Wheb the system woke up, driver is unaware about the interruption so continues to try and use it - without a re-claim. I suppose after a few failures to talk to it, it should reconnect. Alternately systemd units, suspend-resume scripts, or similar mechanism can get the driver restarted.
