### ISSUE TITLE
Hardware compatibility list - Web Page Broken?

### ISSUE THREAD

**Issue by gitisz** [networkupstools/nut#1681]
Is this page now working?
![image](https://user-images.githubusercontent.com/4492953/196284648-5c56869a-4d19-43d3-9bfd-942ec0981b19.png)
I don't see any data like I did before.

**Comment by jimklimov** [comment]
Thanks, seems odd indeed. Maybe the page generator failed, I'll take a look.

**Comment by jimklimov** [comment]
Thanks again, trying a fix. Seems parallel build was stepping on its own toes.
