### ISSUE TITLE
New tool to communicate with NUT server on Windows

### ISSUE THREAD

**Issue by nslythe** [networkupstools/nut#1730]
Hi
I wrote a new software to communicate with NUT Server in Windwos service to initiate a safe shudown when UPS is FSD or LB.
Can you add this url to the thirdparty software to let know NUT user this software exists.

[https://github.com/nslythe/NUTService](https://github.com/nslythe/NUTService)

Thanks

**Comment by jimklimov** [comment]
Now online - https://networkupstools.org/projects.html#_a_href_https_github_com_nslythe_nutservice_nutservice_and_c_nutclient_a

**Comment by jimklimov** [comment]
FYI: There are several typos in your README, the kind of char-swaps I make when typing too fast on an uncomfortable keyboard. Let a spellchecker hover over it :)
