### ISSUE TITLE
winNUT-Client Error/Bug

### ISSUE THREAD

**Issue by Samir-driod** [networkupstools/nut#1733]
[Crash_Report_14-12-2022_21-34-11.txt](https://github.com/networkupstools/nut/files/10239931/Crash_Report_14-12-2022_21-34-11.txt)

I have an Error When I want to start a Client. I reinstall it and it didn't work.
Can En-one help.

Link To Crash_Report: 
[Crash_Report_14-12-2022_21-34-11.txt](https://github.com/networkupstools/nut/files/10239931/Crash_Report_14-12-2022_21-34-11.txt)

**Comment by jimklimov** [comment]
WinNUT (which variant BTW?) is a community project, so can't say much about it. Maybe post on their issue tracker too...

FWIW did you try NUT for Windows builds (e.g. recent master from Appveyor CI)?

**Comment by jimklimov** [comment]
@Samir-driod : seems like https://github.com/gawindx/WinNUT-Client/issues/138 is about the same issue - and a workaround.
