### ISSUE TITLE
Installation docs unclear

### ISSUE THREAD

**Issue by kondas** [networkupstools/nut#1750]
The documentation (INSTALL.nut) is unclear. The mentioned "configure" script is not available in the repository. The Install / Build procedure is not possible from the repository following the instructions. Please updated instructions for manual install.

**Comment by jimklimov** [comment]
As elsewhere, you use autoconf to generate `configure` script for your system from `configure.ac` template (result is included in tarballs and matches the instruction, to reduce build-time dependencies but risking portability to an extent). In NUT this is automated by `autogen.sh` helper script.

**Comment by kondas** [comment]
Thank You for the clarification, i'm not familiar with `autoconf` (yet). I will make a suggestion to modify INSTALL.nut to be more comprehendable for the layman like me in a PR soon. Happy new year!

**Comment by jimklimov** [comment]
Note: I've updated the text - see https://github.com/networkupstools/nut/pull/1752/files

If you think further (yet compact) layman refining would be useful, please do post a PR :)
