### ISSUE TITLE
Typo in libusb{0,1}.c

### ISSUE THREAD

**Issue by kolbai** [networkupstools/nut#1797]
I am not sure, but looks like it should be 9, not 8:
https://github.com/networkupstools/nut/blob/e0a15cc6b9300fa860a61730f59ab99038d952ac/drivers/libusb1.c#L515
https://github.com/networkupstools/nut/blob/e0a15cc6b9300fa860a61730f59ab99038d952ac/drivers/libusb0.c#L466

**Comment by jimklimov** [comment]
The links currently point to upsdebugx messages, maybe text shifted after a PR merge. Can you please re-check which commit you referred to? Maybe change the "master" in URLs above to that commit-id?

**Comment by kolbai** [comment]
Updated URLs.
