### ISSUE TITLE
grep issues

### ISSUE THREAD

**Issue by neilromig** [networkupstools/nut#1827]
Running NUT 2.8.0 on Arch Linux I get warnings relating to egrep usage which come from nut-driver-enumerator.sh:

`nut-driver@myups[478]: egrep: warning: egrep is obsolescent; using grep -E`

I also see this (which I have been unable to track down as yet):

`nut-driver@myups[426]: grep: warning: stray \ before #`

**Comment by jimklimov** [comment]
Thanks. The `egrep` suggestions were fixed some time ago (maybe after 2.8.0 release). One legacy-build target complained back, but had an XPG alternative.

Not sure I saw the other one, but there were some syntax-fixes it could be part of.

Do you have a chance to try the variant from master branch?

**Comment by neilromig** [comment]
I have compiled from master branch (via Arch AUR repository) and comparing files I have worked out the offending grep is the last line of function upslist_normalizeFile_filter() in nut-driver-enumerator.sh:

`grep -E '([\[\=]|^[^ '"$TABCHAR"']*$|^[^ '"$TABCHAR"']*[ '"$TABCHAR"']*\#.*$)'`

So, I have removed the "stray \" at the end of the expression as it seems surplus to requirements, the hash having no special meaning as far as I can determine from reading the grep man page.

Expression is now:

`grep -E '([\[\=]|^[^ '"$TABCHAR"']*$|^[^ '"$TABCHAR"']*[ '"$TABCHAR"']*#.*$)'`

**Comment by jimklimov** [comment]
Thanks! Sort of odd of them to complain about a valid regex (all chars *may* be escaped, for a bit of expensive overkill), but I guess also nice of them to raise noise and cause optimization :)

**Comment by jimklimov** [comment]
Care to post a PR in your name? :)
