### ISSUE TITLE
BlueWalker PowerWalker UPS VFI1500 CGPF1

### ISSUE THREAD

**Issue by pfSecure** [networkupstools/nut#1894]
HI, just bought an new UPS for 2 weeks ago. It start giving me this error message:
Communications with UPS ups@10.10.10.91 lost
Communications with UPS ups@10.10.10.91 established

ubuntu@RasPI4-1:~$ sudo nut-scanner -U
SNMP library not found. SNMP search disabled.
Neon library not found. XML search disabled.
IPMI library not found. IPMI search disabled.
Scanning USB bus.
[nutdev1]
        driver = "blazer_usb"
        port = "auto"
        vendorid = "0665"
        productid = "5161"
        product = "OLHV1K5"
        serial = "XXXXXXXXXXXX"
        bus = "001"

I see the UPS PowerWalker VFI 1000 CG PF1 are using USB driver: nutdrv_gx. But that one does not work on my UPS.
Any plan to add support for this one?

https://powerwalker.com/product/10122109/

Thanks in advance

**Comment by jimklimov** [comment]
Which NUT version? Seems to not be the latest codebase...

How do you start it - e.g. as service or on command line, rc.local, etc - then did you ruke out other ways the OS can auto-start the driver and ao conflict?

Did you rule out OS/env issues (cable noise, USB hub going to powersaving sleep, etc)?

Please also review other issues tagged for Raspberry. We have quite a few, which may be a testament to their popularity, or quality, or both...
