### ISSUE TITLE
Want a way to dump driver state at run-time

### ISSUE THREAD

**Issue by jimklimov** [networkupstools/nut#1907]
Sort of like `upsc`, but without an `upsd` server and a further client. Sort of like `drivername -d N` option but without starting a new driver to dump after N loops and exiting.

This can help a lot during driver development and troubleshooting.

In a way related to earlier efforts with #1771 / #1767

**Comment by jimklimov** [comment]
One way to address this was proposed in PR #1906, although it just handles `SIGUSR2` with the same `dstate_dump()` as the `-d N` handling (without the exit), and so is limited to driver run-times with stdout/stderr streams not closed (no-op otherwise - e.g. for drivers that got backgrounded by default).

**Comment by aquette** [comment]
Can't it be the -d <infinite>?

**Comment by jimklimov** [comment]
Well, ideas are welcome - but note that the plan here is to get a data dump from a running driver that might be behaving strangely, etc. and perhaps without/regardless of a data server nearby.

This differs from a data dump made by a driver just started for the purpose, as in existing `-d N` operations useful especially to check how a new driver build sees your device, without carefully configuring the build for replacing an existing (packaged) NUT until you verify there is benefit in doing so.

In the currently proposed implementation for this "run-time dump" the action is triggered by a signal. Surely, another driver process could send the signal, similarly to how `upsd -c reload` etc. works, and which could be a next step. The question would however be how to get that data to caller (e.g. to report on its stdout), especially if the normally running driver has lost its stdout. Wondering: can the same pipe/socket be used for many dialogues (e.g. driver-server AND driver-driver) safely?..
