### ISSUE TITLE
Option to ignore FSD in nutdrv_qx?

### ISSUE THREAD

**Issue by clepple** [networkupstools/nut#195]
From http://article.gmane.org/gmane.comp.monitoring.nut.devel/6876:

> I had running OpenMediaVault server with NUT 2.4.3 megatec_usb driver. After the OMV upgrade, NUT also upgraded to 2.6.4. I realised that megatec_usb removed in this version. So I have configured to use blazer_usb driver. However NUT behaves incorrectly after switching blazer_usb. System is being halted upon booted up.
> ...
> `ups.mfr: TUNCMATIK`
> `ups.model: DG1200VA`
> ...
> `ups.status: ALARM OL FSD`

As a result, the system shuts down immediately.

@zykh, any thoughts on this? Did I overlook some other option which could help? (We can't use override.* because that will mask all of `ups.status`)

**Comment by zykh** [comment]
Looked at the logs and just added 'ignoresab' (IGNORE 'Status Active' Bit) flag in nutdrv_qx - this should do the trick.
