### ISSUE TITLE
Looks like release tarball `nut-2.8.0.tar.gz` does not exist anymore

### ISSUE THREAD

**Issue by chenrui333** [networkupstools/nut#1971]
👋 trying to upgrade openssl dependency for nut, I found that the artifact (`nut-2.8.0.tar.gz`) is gone. Create this issue to confirm if that is intended. Thanks!

(this is the full url, "https://github.com/networkupstools/nut/releases/download/v2.8.0/nut-2.8.0.tar.gz")

https://github.com/Homebrew/homebrew-core/pull/134565

**Comment by chenrui333** [comment]
updated the artifact url instead on the linked PR

**Comment by jimklimov** [comment]
Hello, sorry for a sort of late reply - I've re-posted https://github.com/networkupstools/nut/releases/tag/v2.8.0 (based on the originally named git tag) so the original URL patterns will work again, hopefully.

I'll add a note on this to NUT Maintainer guide.
