### ISSUE TITLE
upssched high CPU usage on FreeBSD

### ISSUE THREAD

**Issue by 0xdd-co** [networkupstools/nut#2009]
Currently running nut 2.8.0_23 compiled from ports on FreeBSD. I noticed that any timers that I set in `upssched.conf` occupy ~90+% CPU usage of a single core indefinitely while a timer is running. Occurs with both `upshid-ups` and `dummy-ups` drivers.

`upssched.conf` below:

```
CMDSCRIPT /opt/local/bin/upssched-cmd

PIPEFN /var/db/nut/upssched/upssched.pipe
LOCKFN /var/db/nut/upssched/upssched.lock

AT COMMOK cyberpower@localhost EXECUTE cyberpower-commok
AT COMMBAD cyberpower@localhost EXECUTE cyberpower-commbad
AT ONBATT cyberpower@localhost EXECUTE cyberpower-onbatt
AT ONBATT cyberpower@localhost START-TIMER cyberpower-onbatt-timer 120
AT LOWBATT cyberpower@localhost START-TIMER cyberpower-batt-critical 15
AT ONLINE cyberpower@localhost EXECUTE cyberpower-online
AT ONLINE cyberpower@localhost CANCEL-TIMER cyberpower-onbatt-timer
AT ONLINE cyberpower@localhost CANCEL-TIMER cyberpower-batt-critical

AT ONBATT heartbeat@localhost CANCEL-TIMER heartbeat-failure-timer
AT ONBATT heartbeat@localhost START-TIMER heartbeat-failure-timer 660
```

**Comment by jimklimov** [comment]
I think this was reported and fixed a month or two back, can check by upssched label, but there was no NUT release since then ;(

**Comment by cschuber** [comment]
The user could try the sysutils/nut-devel port/package. It tracks mainline development and is at most one month behind development -- though I try to keep it within a week if possible.

**Comment by jimklimov** [comment]
@0xdd-co : Cheers, did you have a chance to try the newer NUT port? Is the issue solved there for you?

**Comment by 0xdd-co** [comment]
@cschuber @jimklimov Thanks to you both for your help! I did indeed try the nut-devel port and it resolves the issue. Thanks again!

**Comment by fabiengagne** [comment]
I think I have this same issue using TrueNAS Scale 23.10.0.1 where there's a UPS service (NUT) is packaged in. One thread of the CPU goes to 100% as soon and as long as my UPS goes on batteries. I think 2.8.0 is the version included (as reported by /lib/nut/upsmon -V).

**Comment by fabiomsouto** [comment]
I can confirm the same issue that @fabiengagne is having.
