### ISSUE TITLE
nutdrv_qx reopen never triggers

### ISSUE THREAD

**Issue by EchterAgo** [networkupstools/nut#2079]
When checking for #2063 how other drivers handle device reopen, I noticed that `nutdrv_qx` never really triggers its reopen code path.

The `reopen_matcher` gets used in `qc_command` only if `udev == NULL` and IIUC `udev` never will be set to NULL.

**Comment by jimklimov** [comment]
I think the `fallthrough_case_reconnect` a few lines below that check should handle this - closes the device and sets `udev=NULL`.

Something to check (if this non-reconnect situation does happen in practice) is whether the conditions leading to such closure are captured by the switch/case correctly. If truly not, then there are several other USB-capable drivers to revisit similarly :)

**Comment by EchterAgo** [comment]
Heh, how did I miss that? Closing this.
