### ISSUE TITLE
compiler warnings: localtime and gmtime

### ISSUE THREAD

**Issue by desertwitch** [networkupstools/nut#2115]
This is not really a functional issue but rather one that - I think - warrants fixing for a potential 2.8.1. release. It could lead end-users or packagers into thinking there's a problem with their builds that needs urgent fixing, when in fact there's not. This could even, in turn, lead to potential new problems going down that road of finding such a fix. At least that's what happened for me, attempting to mess around with custom CFLAGS while trying to resolve a building problem that was - upon investigation of the source code - essentially non-existent despite the information reported in the logs.

Not all systems have both `localtime_r` and `localtime_s` or `gmtime_r` and `gmtime_s` respectively, that's why we already have this workaround in the `timehead.h` - so that the functions existent on the system are used instead:

https://github.com/networkupstools/nut/blob/330a00ef2934bbdf27b003edbfab55c07cf9d31a/include/timehead.h#L47-L74

Still the configure checks at present lead us into believing a **Required C library routine** was not found:

```
checking for localtime_r... yes
checking for localtime_s... no
configure: WARNING: Required C library routine not found; try adding -D_POSIX_C_SOURCE=200112L
checking for gmtime_r... yes
checking for gmtime_s... no
configure: WARNING: Required C library routine not found; try adding -D_POSIX_C_SOURCE=200112L
```

These log messages sound like an urgent, showstopper type of problem that needs fixing, required routines missing after all.
In fact though - they're not - as the code is simply substituting `_r` with `_s` and vice-versa (as seen in the code snipped above).

This behaviour stems from `configure.ac`:
https://github.com/networkupstools/nut/blob/330a00ef2934bbdf27b003edbfab55c07cf9d31a/configure.ac#L731-L732

Perhaps there is a better way to check if either function is present, rather than requiring both?

**Comment by jimklimov** [comment]
Probably there is, now that we are aware about the issue :)
The original check existed for some time and was extended later with NUT for Windows effort, IIRC. So as long as it was functional, it was not a big bother...
