### ISSUE TITLE
Incorrect CRC calculation in Riello driver.

### ISSUE THREAD

**Issue by cool0nik** [networkupstools/nut#2137]
In file nut/drivers/riello.c

This line:
					pom = (pom << 8) ^ (pom << 3) ^ (pom >> 4);
was replaced by:
					pom  = (uint16_t)(pom << 8);
					pom ^= (pom << 3);
					pom ^= (pom >> 4);
					
This is wrong changes.
The result of CRC calculation was changed.
UPS does not working with this change and change should be reverted.

This "optimization" was introduced here:
https://github.com/networkupstools/nut/commit/6a2e042e3e0fa6a821a9edb444f042fbc81723c3

Issue was found during upgrade Debein 11 -> 12.
from 
Network UPS Tools - Riello serial driver 0.03 (2.7.4)
to
Network UPS Tools - Riello serial driver 0.07 (2.8.0)

**Comment by jimklimov** [comment]
Thanks for the report. Would you be able to check the PR above, with e.g. https://github.com/networkupstools/nut/wiki/Building-NUT-for-in%E2%80%90place-upgrades-or-non%E2%80%90disruptive-tests ?
