### ISSUE TITLE
Question about changing subdriver

### ISSUE THREAD

**Issue by Voidstranger** [networkupstools/nut#2157]
I have NUT 2.8.1 running on OpenWrt router. Using usb-hid driver. How can I change in config file subdriver to MGE?

**Comment by jimklimov** [comment]
Presumably (new feature) you'd open ups.conf and type `subdriver=...` in the device's section. List of subdriver strings (caught by regexes generally) can be seen in the help message of your driver's build.

**Comment by Voidstranger** [comment]
Ok, thank you.
