### ISSUE TITLE
PyNUTClient needs `telnetlib`

### ISSUE THREAD

**Issue by mtelka** [networkupstools/nut#2181]
The PyNUTClient package at PyPI needs `telnetlib`:
```
$ grep req PyNUTClient-2.8.1/setup.py
    install_requires=['telnetlib'],
$
```
But such project is not available at PyPI.  I see only [telnetlib3](https://pypi.org/project/telnetlib3/) and [telnetlib2](https://pypi.org/project/telnetlib2/) there.

Is the requirement correct?  If so, where can I find `telnetlib`?

**Comment by jimklimov** [comment]
Seems it is part of Python:
````
$ find /usr -name telnetlib'*'
/usr/lib/python3.8/__pycache__/telnetlib.cpython-38.pyc
/usr/lib/python3.8/telnetlib.py
/usr/lib/python3.9/__pycache__/telnetlib.cpython-39.pyc
/usr/lib/python3.9/telnetlib.py
/usr/lib/python3.10/__pycache__/telnetlib.cpython-310.pyc
/usr/lib/python3.10/telnetlib.py
/usr/lib/python2.7/telnetlib.pyc
/usr/lib/python2.7/telnetlib.py
````
or
````
$ pkg search telnetlib.py
...
basename   file   usr/lib/python3.9/telnetlib.py pkg:/runtime/python-39@3.9.16-2023.0.0.2
...
````

**Comment by jimklimov** [comment]
Are `setup.py` dependencies about listing needed importable modules, or about `pip` downloadables?

**Comment by jimklimov** [comment]
Thanks, can you check if https://test.pypi.org/manage/project/PyNUTClient/release/2.8.1.139/ looks better?

**Comment by mtelka** [comment]
> Thanks, can you check if https://test.pypi.org/manage/project/PyNUTClient/release/2.8.1.139/ looks better?

No, since I have no account there (it asks for Username/Password).  But it looks like what you propose in #2182 should work.

OTOH, it looks like `telnetlib` is [deprecated since Python 3.11](https://docs.python.org/3/library/telnetlib.html) and will be removed soon so you should look at alternatives anyway.

**Comment by jimklimov** [comment]
Yeah, sorry - wrong URL. Posted the public TestPyPI release one in that PR.

**Comment by jimklimov** [comment]
Thanks for the deprecation notice, missed that one. Probably will have to ship a copy along with this module, or go to some low-level networking directly...Or take a look at those separate number-named modules you mentioned.
