### ISSUE TITLE
NUT-Monitor scripts is trying to start NUT-Monitor-py3qt3 instead of NUT-Monitor-py3qt5

### ISSUE THREAD

**Issue by bigon** [networkupstools/nut#2199]
Hello,

At two locations in NUT-Monitor scripts, it's mentioned "qt3" instead of "qt5"

I guess that's a typo

https://github.com/networkupstools/nut/blob/master/scripts/python/app/NUT-Monitor#L51

**Comment by jimklimov** [comment]
Hey, long time no see! :)
Thanks, I suppose it is.
