### ISSUE TITLE
design bug: upsmon spams the logs when cannot talk to driver or when driver cannot talk to ups

### ISSUE THREAD

**Issue by mailinglists35** [networkupstools/nut#2207]
When `nut-monitor` cannot talk to `/lib/nut/$whatever-driver`, or when the communication between the driver and the ups is unavailable, it repeats this message in logs:

```
nov 29 16:06:01 router upsmon[486203]: Poll UPS [nutdev1@localhost] failed - Driver not connected
````

I wish it allowed a configuration directive or a command line argument to only print this message once. the polite behaviour is already exhibited by `upsd`, that only prints an equivalent message once:

````
nov 29 16:10:44 router upsd[476370]: Can't connect to UPS [nutdev1] (nutdrv_qx-serioux): No such file or directory
````

the repeating of message every 5 seconds in logs provides no use to me, and only annoyance instead.

this is literally the equivalent of ups emiting audible beeps - that makes sense in physical world as having the role of catching a human's attention that might not be near it all the time, so it makes perfect sense to repeat the beep, because in physical world you cannot roll back in time to listen to sounds in a room (unless you have a sound recording device)

however in electronic world the logs are monitored, and a single line is sufficient to trigger an alert, because unlike in physical world, an alert does not dissapear once it has been produced, and someone will be able to read it any time later, thus it make no logical sense to repeat the line.

the same when comm is lost: upsd politely tells me **once**

````
Broadcast message from nut@router (somewhere) (Wed Nov 29 16:19:58 2023):

Communications with UPS nutdev1@localhost lost

nov 29 16:19:58 router upsmon[494593]: Poll UPS [nutdev1@localhost] failed - Data stale
nov 29 16:19:58 router upsmon[494593]: Communications with UPS nutdev1@localhost lost
````

while upsmon begins spamming the logs every 5 seconds:
````
nov 29 16:20:13 router upsmon[494593]: Poll UPS [nutdev1@localhost] failed - Data stale
````

**Comment by jimklimov** [comment]
I agree, and a PR is welcome :)

For context, not always not everywhere logs are monitored (so as to make alerts) from them in real time. As a side note, NUT probably predates most of the fancier log-monitoring systems you see today, so the unseen/unborn techs were not a factor in the original design :)

In fact, upsmon has "notifications" to WALL/SYSLOG/EXEC for a number of events and state changes, and those are throttled (IIRC e.g. `wall`ing once in 5 mins by default for Data Stale).

> no logical sense to repeat...

I believe it just runs the polling loop and reports encountered errors. To stderr typically, which is then sysadmin's or packager's "fault" if it ends up logged (though maybe upsdebugx()/upslogx() does ditto or redirect to syslog at some point like forking and/or based on internal config).  It is extra work to remember that the same error was reported on last cycle (such work is the welcome PR) and e.g. report it only for non-zero debug verbosity for some time. Probably the throttling approavh for notifications can be used here.

**Comment by mailinglists35** [comment]
>PR

I am not a programmer, but I am wondering if the code logic that emits the similar log in `upsd` can not be applied to the routine logic blocks in `upsmon`? would it be feasible?

**Comment by jimklimov** [comment]
A bit more sleuthing, and PR #1784 comes up, so it seems I've already fixed that earlier in the busy year and it got fully flushed from memory, oops `-\_(o,o)_/=`

The feature should be part of NUT codebase since January, so would be in v2.8.1 release (issued a month ago). Should not have the off-by-one behavior in v2.8.2 and later, thanks ;)

**Comment by jimklimov** [comment]
Thanks for the report!

While it was ultimately about an issue already solved and published in a NUT release (seems you've never mentioned which one you are running BTW), it also helped discover some issues in the earlier implementation so the next release would be even better :)

**Comment by jjakob** [comment]
I enabled this feature by setting `POLLFAIL_LOG_THROTTLE_MAX 100` in upsmon.conf, but it still logs `upsmon[3375]: UPS ups@192.0.2.30]: connect failed: Connection failure: No route to host` every 5-10 seconds. I think it should only log every 100th occurrence of the error if I understood the docs right (they're not exactly clear what the number actually is)?

nut 2.8.4, Gentoo.
