### ISSUE TITLE
[BUG?] "systemd-tmpfiles --clean" return an error

### ISSUE THREAD

**Issue by ManuLinares** [networkupstools/nut#2210]
```
~ $ sudo systemd-tmpfiles --clean
/usr/lib/tmpfiles.d/nut.conf:1: Duplicate line for path "/run/nut", ignoring.
/usr/lib/tmpfiles.d/nut.conf:2: Duplicate line for path "/var/lib/nut", ignoring.

```

```
~ $ cat /usr/lib/tmpfiles.d/nut.conf
d /run/nut 0700 nut nut -
d /var/lib/nut 0700 nut nut -
z /etc/nut/upsd.conf 0640 root nut -
z /etc/nut/upsd.users 0640 root nut -
z /etc/nut/upsmon.conf 0640 root nut -
```

My system: archlinux, latest everything as of 03-dec-2023

**Comment by jimklimov** [comment]
I suppose this is a packaging bug in that distribution, with their `nut.conf` conflicting with a `/usr/lib/tmpfiles.d/nut-common-tmpfiles.conf` which may be generated and delivered by the NUT vanilla build (if they package and deliver it as well as theirs).

**Comment by ManuLinares** [comment]
Thanks. I don't seem to be able to login to post a bug report in https://gitlab.archlinux.org/archlinux/packaging/packages/nut/-/issues

**Comment by jimklimov** [comment]
Ok, seems there's some traction on Arch Linux side. I guess the issue can be closed here as a not-NUT bug :)
