### ISSUE TITLE
nut-scanner reports non-existent driver for NUT discovery

### ISSUE THREAD

**Issue by aquette** [networkupstools/nut#2236]
When discovering NUT, either with Avahi or old method, the reported driver is "nutclient", which doesn't (yet) exists.
This should be fixed to dummy-ups, which will use the *repeater* mode, while waiting for #2232 

the short term fix is to (example on Debian):
> cd /lib/nut && ln -s dummy-ups nutclient

**Comment by jimklimov** [comment]
Fixed by: #2245
