### ISSUE TITLE
nut-scanner generated conf can cause device-name collisions

### ISSUE THREAD

**Issue by aquette** [networkupstools/nut#2243]
When nut-scanner is called separately, to scan different busses, it will generate similar names for each of these:
* USB scan
> [nutdev1]
> ...
* NUT scan
> [nutdev1]
> ...
* ...

As a result, one can't just redirect nut-scanner outputs directly to ups.conf, without a 'sed' hack workaround.

Solution: simply refine the device names, like "nutdev-[method][id]".
Examples: nutdev-usb1, nutdev-usb2, nutdev-nut1, nutdev-snmp1, ...

**Comment by jimklimov** [comment]
Fixed by #2247
