### ISSUE TITLE
Check that you've installed libusb-dev or equivalent for your distro. Without it, nutdrv_qx is serial-only.

### ISSUE THREAD

**Issue by Ariessanea1** [networkupstools/nut#2259]
Check that you've installed libusb-dev or equivalent for your distro. Without it, nutdrv_qx is serial-only.

_Originally posted by @jimklimov in https://github.com/networkupstools/nut/issues/2219#issuecomment-1883591220_

**Comment by jimklimov** [comment]
What is this new issue about? :)

On NUT side, we check it and report on the wall of text and later summary of `configure` script, with USB being just one of a gazillion dependencies and optional build variants. Probably yours said that auto-detection for building against libusb failed, it was not required (by some explicit `--with-usb`), so skipped.

Your build probably lacks a few drivers with `usb` in the name (`blazer_usb`, `usbhid-ups`, etc.)

FWIW though, the `nutdrv_qx` being special with multiple media support in one binary, its identification banner could reflect the build circumstances to ease trouble-shooting.
