### ISSUE TITLE
No server entries in the DNS UI show up in Work Profile:

### ISSUE THREAD

**Issue by Ariessanea1** [networkupstools/nut#2276]
No server entries in the DNS UI show up in Work Profile:

<details>
<summary>screenshots of DNS pages</summary>
screenshot1

![Screenshot_20231212-183326_Rethink](https://github.com/celzero/rethink-app/assets/133971463/565add93-106c-46be-ace6-8f2e4f3684b8)
screenshot2
![Screenshot_20231212-183316_Rethink](https://github.com/celzero/rethink-app/assets/133971463/e7aa4757-c287-48eb-892f-fd06e10e1ac6)
screenshot3
![Screenshot_20231212-183311_Rethink](https://github.com/celzero/rethink-app/assets/133971463/52c811e8-9a44-4b68-ab37-abcac6e91b02)
screenshot4
![Screenshot_20231212-183321_Rethink](https://github.com/celzero/rethink-app/assets/133971463/47e9bb6c-408b-442d-a72d-2a1fe4b5604a)
screenshot5
![Screenshot_20231212-183332_Rethink](https://github.com/celzero/rethink-app/assets/133971463/335f5ce8-4709-4967-b95a-1124e057b038)
</details>

Logfile
[bugreport_0.txt](https://github.com/celzero/rethink-app/files/13649836/bugreport_0.txt)

_Originally posted by @Stu75e in https://github.com/celzero/rethink-app/issues/1162_

**Comment by jimklimov** [comment]
Please stop the useless spam, it is tedious enough to go over meaningful posts already!
