### ISSUE TITLE
SNMP: delta_ups-mib.c: is "splite-phase" a real word?

### ISSUE THREAD

**Issue by jimklimov** [networkupstools/nut#2302]
https://github.com/networkupstools/nut/blob/dcbb2ba041fd1feaff924f3edd388d2f75c350ae/drivers/delta_ups-mib.c#L41-L48

@aquette : in item 5, is it "splite" (some vendor key word?) or "split" phase here? Any ideas? :)

_Originally posted by @jimklimov in https://github.com/networkupstools/nut/pull/2285#discussion_r1484256970_

**Comment by aquette** [comment]
Split-phase 😉
