### ISSUE TITLE
nutclient: stringset_to_strarr() and stringvector_to_strarr() only work for one element

### ISSUE THREAD

**Issue by clepple** [networkupstools/nut#232]
reported by Paul Vermeer: http://article.gmane.org/gmane.comp.monitoring.nut.user/9331

> Both functions stringset_to_strarr and stringvector_to_strarr have a similar bug in play. Although trivial in code, the coded function does not operate as intended.
> The pointer increment is missing (see added line marked yellow below [pstr++;]), which results in the same element being updated over and over again, and then only leaving the last element of the list in the array.

**Comment by aquette** [comment]
@balooloo : if you have 5 mn to take a look at that one also, would be great. Please self assign if you can, thx.

**Comment by aquette** [comment]
Closed through PR #284
