### ISSUE TITLE
Summary PowerWalker VFI 3000 CG PF1

### ISSUE THREAD

**Issue by derritter88** [networkupstools/nut#2376]
I am using a PowerWalker VFI 3000 CG PF1 UPS with following ups.conf settings:

```
[powerwalker]
        driver = "nutdrv_qx"
        port = "auto"
        protocol = voltronic
        novendor
        product = "OLHV3K0"
        desc = "PowerWalker VFI 3000 CG PF1"
        pollinterval = 15
        serial = "ID83322106102166"
        runtimecal = 180,100,600,50
```
Do note that `novendor` parameter is essential as otherwise the UPS will stop providing data to nut-driver.
`runtimecal` values are added manual as the UPS itself does not provide any runtime information

With nut 2.8.0 it takes some time until the driver is loaded and can be used.

I do get following values:
```
Init SSL without certificate database
battery.charge: 100
battery.energysave: no
battery.runtime: 1800
battery.voltage: 82.00
battery.voltage.high: 78.00
battery.voltage.low: 62.40
battery.voltage.nominal: 72.0
device.serial: ID83322106102166
device.type: ups
driver.flag.novendor: enabled
driver.name: nutdrv_qx
driver.parameter.pollfreq: 30
driver.parameter.pollinterval: 15
driver.parameter.port: auto
driver.parameter.product: OLHV3K0
driver.parameter.protocol: voltronic
driver.parameter.runtimecal: 180,100,600,50
driver.parameter.serial: IDxxxxxxx
driver.parameter.synchronous: auto
driver.version: 2.8.0
driver.version.data: Voltronic 0.06
driver.version.internal: 0.32
driver.version.usb: libusb-1.0.26 (API: 0x1000109)
input.current.nominal: 13.0
input.frequency: 50.0
input.frequency.high: 53.0
input.frequency.low: 47.0
input.frequency.nominal: 50.0
input.transfer.high: 242
input.transfer.high.max: 254
input.transfer.high.min: 237
input.transfer.low: 218
input.transfer.low.max: 223
input.transfer.low.min: 206
input.voltage: 234.5
input.voltage.nominal: 230.0
outlet.0.switchable: no
output.current: 0.6
output.current.nominal: 13
output.frequency: 49.9
output.frequency.nominal: 50.0
output.voltage: 229.1
output.voltage.nominal: 230.0
ups.beeper.status: enabled
ups.delay.shutdown: 30
ups.delay.start: 180
ups.firmware: 01574.05
ups.firmware.aux: P01
ups.load: 6
ups.productid: 5161
ups.start.battery: yes
ups.status: OL
ups.temperature: 24.1
ups.type: online
ups.vendorid: 0665
```

What I do not get would be the remaining runtime.

**Comment by derritter88** [comment]
Command `test.battery.stop` is not working

**Comment by derritter88** [comment]
Also battery value % is different from NUT vs LCD screen on UPS.

10 % according to LCD vs 73 % according to NUT.

**Comment by derritter88** [comment]
NUT on version 2.7.4 printed the proper values with nutdrv_qx

**Comment by derritter88** [comment]
`protocol=voltronic` solved the problem

**Comment by jimklimov** [comment]
@derritter88 : to clarify, did the change to `voltronic` protocol fix the issues in later posts (battery percentage, runtime, commands)?

Is the data dump in top post "partially bad" from the original attempt, or the "good" one after the edit? If not, can you post the "good" data also (not overwriting the earlier post, so both examples can go to the DDL eventually), please?

**Comment by derritter88** [comment]
@jimklimov Hi Jim, I edited my initial post to `voltronic` to get the proper values from the UPS.
The data dump is from a "bad" driver (megatronic) but to be honest: I had to replace the PowerWalker by an Eaton as the UPS kept "locking in" and did not continue to communicate via the driver. Due to that I had to shutdown my servers to power off the UPS and turn it back on to "enable" the USB connection.

From a Linux perspective the USB was always there but the data got stale.

**Comment by derritter88** [comment]
It would be interesting if different users of PowerWalker/BlueWalker devices experience the same problems which I had.

**Comment by derritter88** [comment]
But as this UPS is now spare I would be happy to test anything for you to see if it would solve me previous mentioned troubles

**Comment by derritter88** [comment]
I removed the vendor stuff to see if it disconnects again after some days.
Current config would be:
```
[powerwalker]
        driver = "nutdrv_qx"
        port = "auto"
        protocol = voltronic
        #subdriver = cypress
        novendor
        product = "OLHV3K0"
        desc = "PowerWalker VFI 3000 CG PF1"
        pollinterval = 15
        serial = "xxxxxx"
        runtimecal = 180,100,600,50
```

**Comment by derritter88** [comment]
@jimklimov I think I found the working solution so the UPS does not stop talking to the driver:
```
[powerwalker]
        driver = "nutdrv_qx"
        port = "auto"
        protocol = voltronic
        #subdriver = cypress
        novendor
        product = "OLHV3K0"
        desc = "PowerWalker VFI 3000 CG PF1"
        pollinterval = 15
        serial = "ID83322106102166"
        runtimecal = 180,100,600,50
```

It's important to use "novendor" as otherwise the driver stops getting data after some time.
The only thing I am still struggeling is that the driver gets stale from time to time - even when playing around with `pollinterval`.


Do you want me to adopt the original issue description?

**Comment by jimklimov** [comment]
Yes, I think that would be good - thanks!

**Comment by derritter88** [comment]
Done & closed the ticket.

**Comment by jimklimov** [comment]
One more bit, please: How many of the original "complaints" about available values/commands remain valid with your latest configuration?

**Comment by derritter88** [comment]
None - I untouched the latest config for about 1.5 weeks and the UPS remains available to the nut-driver with the given values.

**Comment by jimklimov** [comment]
> What I do not get would be the remaining runtime.

Seems available in the latest update of the data dump.

> Command test.battery.stop is not working

???

> Also battery value % is different from NUT vs LCD screen on UPS. 10 % according to LCD vs 73 % according to NUT.

???

> NUT on version 2.7.4 printed the proper values with nutdrv_qx

Are these "on par" now? :)

**Comment by derritter88** [comment]
I would get following options:

```
Instant commands supported on UPS [powerwalker]:

beeper.disable - Disable the UPS beeper
beeper.enable - Enable the UPS beeper
beeper.toggle - Toggle the UPS beeper
bypass.start - Put the UPS in bypass mode
bypass.stop - Take the UPS out of bypass mode
load.off - Turn off the load immediately
load.on - Turn on the load immediately
shutdown.return - Turn off the load and return when power is back
shutdown.stayoff - Turn off the load and remain off
shutdown.stop - Stop a shutdown in progress
test.battery.start - Start a battery test
test.battery.start.deep - Start a deep battery test
test.battery.start.quick - Start a quick battery test
test.battery.stop - Stop the battery test
```

**Comment by derritter88** [comment]
Additional I haven't checked anything additional like again running a deep battery test.

**Comment by derritter88** [comment]
`test.battery.start.quick` worked.

**Comment by derritter88** [comment]
`test.battery.start.deep` also works.

**Comment by derritter88** [comment]
`test.battery.stop` also works.

**Comment by derritter88** [comment]
`bypass.start/stop` seems not to work

**Comment by derritter88** [comment]
> > What I do not get would be the remaining runtime.
> 
> Seems available in the latest update of the data dump.
> 
> > Command test.battery.stop is not working
> 
> ???
> 
> > Also battery value % is different from NUT vs LCD screen on UPS. 10 % according to LCD vs 73 % according to NUT.
> 
> ???
> 
> > NUT on version 2.7.4 printed the proper values with nutdrv_qx
> 
> Are these "on par" now? :)

The remaining runtime is being done via `runtimecal = 180,100,600,50` at the driver settings.
