### ISSUE TITLE
Driver riello_ser have the same issue #1685 of riello_usb about battery capacity and runtime

### ISSUE THREAD

**Issue by ramponis** [networkupstools/nut#2390]
This issue
https://github.com/networkupstools/nut/issues/1685

was already solved with localcalculation feature

Is it possible to integrate the localcalculation functionality also in serial driver?

Thank you

**Comment by ramponis** [comment]
I don't think to be able to modify the source by myself.
If you can do it, I will try to build the source and test it.
Then I will give you a feedback.

Thank you

**Comment by jimklimov** [comment]
Give this a shot: #2391

When following the https://github.com/networkupstools/nut/wiki/Building-NUT-for-in%E2%80%90place-upgrades-or-non%E2%80%90disruptive-tests instructions, be sure to check out the PR source branch:
````
:; git clone https://github.com/jimklimov/nut -b issue-2390
:; cd nut
...
````

**Comment by ramponis** [comment]
It works!!!

Thank you

**Comment by jimklimov** [comment]
Super, thanks!
