### ISSUE TITLE
How to Set ECO/HE mode in Eaton 9E model

### ISSUE THREAD

**Issue by masterwishx** [networkupstools/nut#2485]
Using nut plugin v2.8.2 in Unraid.
@jimklimov @arnaudquette-eaton 
Is any way I can set ECO mode (OL BYPASS)
by nut commands, or maybe by setting high /low output voltage?

**Comment by masterwishx** [comment]
By button on ups I can only set bypass mode not ECO mode

**Comment by jimklimov** [comment]
There does not currently seem to be a way to manage or even name the ECO mode in NUT at all, posted issue #2495 to track that.
