### ISSUE TITLE
Add AEG UPS

### ISSUE THREAD

**Issue by aquette** [networkupstools/nut#249]
as per https://www.mail-archive.com/nut-upsdev@lists.alioth.debian.org/msg04120.html

Need the list of supported devices, with names, to update the HCL (http://www.networkupstools.org/stable-hcl.html), to differentiate from already supported AEG devices:
http://www.networkupstools.org/stable-hcl.html?Manufacturer=AEG%20Power%20Solutions

**Comment by CindyZhan2015** [comment]
I'm not sure whether model names is the information do need. 
Model names: PROTECT NAS, PROTECT B

**Comment by aquette** [comment]
these devices are basically rebranded Eaton 5SC, with modified USB VendorID and Strings.
