### ISSUE TITLE
UPSRW unexpected response from upsd

### ISSUE THREAD

**Issue by JordyWingelaar** [networkupstools/nut#2499]
Hi,

When trying to set UPS variables, using the upsrw command, I am not able to succeed.
When trying to change the battery.mfr.date, because I changed the battery inside the UPS, the command returns with an error.

`upsrw "Utilities@localhost" ` returns with the list of viariables to edit.
`upsrw -s "battery.mfr.date" -u upsmon secret "Utilities@localhost"` returns with the question for a new value. When providing one, it returns with a error.
`upsrw -s "battery.mfr.date=20240601" -u upsmon secret "Utilities@localhost"` returns with a error.
upsrw -s "

No matter what I try, it returns with the error Unknown UPS. To me this eems weird, as I am able to list the variables, so the UPS is recognised.

Can anyone help me in the right direction?

![Screenshot 2024-06-29 at 21 07 28](https://github.com/networkupstools/nut/assets/153375415/3a5c2cbf-510a-4af4-b363-ccd2e17aaf5f)

![Screenshot 2024-06-29 at 21 10 05](https://github.com/networkupstools/nut/assets/153375415/eea6f72a-16c1-497f-b828-7ffe69e2b084)

**Comment by clepple** [comment]
The `secret` parameter is probably being parsed as the UPS name. Try `-p secret` (or omit it, and provide the password when prompted).

Reference: https://networkupstools.org/docs/man/upsrw.html#_options
