### ISSUE TITLE
blazer / Megatec/Q1 / Qx driver Gen4

### ISSUE THREAD

**Issue by aquette** [networkupstools/nut#25]
Create the 4th generation driver to address all older Q1 and newer Q5 / QFS protocol variations.

The general idea is to have something between the current blazer\* and usbhid-ups like claiming and data mapping structure.

A special care must be taken to old dumb things:
current parameters have to be kept, and a "force q1" should probably be added.

**Comment by jimklimov** [comment]
Historic note: per 6b6ec952681b055614c4c77d8fb21da26a6df209 this later became the `nutdrv_qx` driver.
