### ISSUE TITLE
something wrong with char

### ISSUE THREAD

**Issue by phlnil** [networkupstools/nut#2543]
Thank you for this gem of sw!
I am getting an error as prompted to my command :systemctl status nut-client on proxmox node (slave).
![immagine](https://github.com/user-attachments/assets/4719d81e-5918-4abc-89ec-ec73b618e549)

Why ? 
config issue ? or something wrong with the reply from ups ?

**Comment by jimklimov** [comment]
Never saw that one. A wild guess: is your UPS (or server host name) non-ASCII? Gotta check if byte values over 127 are allowed in such strings.

**Comment by phlnil** [comment]
Thank you, I also checked all fields... but no strange chars at all ([A..z]). 
upsc comand from the client retrieve all info flawless.
That chars where could be ?

**Comment by jimklimov** [comment]
The message would come from some security hardening per commit https://github.com/networkupstools/nut/commit/2d6b47296c2b9345a603054681a4ecfc902d9ebb with current version seen here:
* https://github.com/networkupstools/nut/blob/5530760f6b050d8d9343b2e197e12ecfefe1629a/common/parseconf.c#L184-L189

One more thing to check for is UTF-8 encoding, your repeating sequence `0xe2 0x80 0xNN` looks like a symptom.
`...0x9c` and `...0x9d` in particular are pretty quotes (left/right), and `...0x93` is a dash - probably you've pasted sample configs from a web page or word/pdf/... document that was rendered friendlier to humans than to computers?

For that matter, check if your `ups.conf` or similar NUT configs were not last saved in an Unicode-capable editor which might embed also the first 3 bytes as a BOM (Byte order mark) `0xEF 0xBB 0xBF`.

**Comment by phlnil** [comment]
Thank you ! anyway I pasted using always using _nano_ I will inspect any other file  ups.conf is yet untouched.
Also on the server side could be checked ? (I am just playing (my bad)  for the client/slave side)

**Comment by jimklimov** [comment]
Well, here I think the most relevant file to check (first) would be `upsmon.conf` since this is the program which complains.

**Comment by phlnil** [comment]
maybe it's solved ! THANK YOU
![immagine](https://github.com/user-attachments/assets/e349263e-a3a6-4a52-9550-5fb356fb9121)
maybe the " « » ‘ ’ “ ” was not the right one !
