### ISSUE TITLE
CI: `clang-18` complains about a lot of `switch` clauses without a `default` label

### ISSUE THREAD

**Issue by jimklimov** [networkupstools/nut#2588]
Bumped the NUT CI farm OI build agent which delivers `clang-18` and `gcc-13` as options now, but the former dislikes `./ci_build.sh` with a few dozen "incomplete" `switch` clauses.

The latter reproduced the #2585 issue.

**Comment by biergaizi** [comment]
Right now the fix is to add `default: break` blindly to all "impossible" conditions. But wouldn't it be more appropriate to abort the program with an assertion failure in the `default` branch (e.g. `fatalx(EXIT_FAILURE...)`) to both suppress the warning and add defensive programming at the same time?

**Comment by jimklimov** [comment]
Could be worth some experimentation... I just wonder how many end-users that unilateral switch to `fatalx` would break.

With things where we know all expectable values (*our* enums and equivalents) this is reasonable. With values returned by third-party code (e.g. depending at run-time on shared libraries available in end-user deployments and/or headers at time of build) this is much more questionable, and given that many cases might need actual devices AND platform together to test, it would be adventurous...

Maybe some semi-reasonable way forward would be to use a macro for that default handling - including the `default:` label if macros can do it to issue a warning debug message and a `break` in common builds, or a `fatalx()` in defensive builds, and NO `default:` label in `fightwarn` CI test builds to have them fail due to compiler warnings at least on the library combos we have in the NUT CI farm.

The next layer of complexity I suppose would be the `switch` handling cases that a particular system may never offer, and compiler knows that. Some may be hidden by `#ifdef SOME_ENUMLIKE_VALUE` some maybe not.

On the other hand, if the library behaves in some way we did not expect, a failure may be worth it to investigate and adapt to what it actually does. Except that end-users would be out there with broken deployments that instead of doing 90% of the work do nothing until they get a new package (or the courage to make a custom build).

Like the recent forays with OpenSSL occasional-failure investigation that started around #202 and hopefully will get solved in #3344 (spanning a decade!) where the code expected particular returns for an immediate success, and did not expect (nor implement behaviors) for a retry. Philosophical question: should those servers/clients have crashed or just refused to to use SSL but otherwise be functional (e.g. if the configuration is "try but not require")?

**Comment by biergaizi** [comment]
Yes, there's a real risk that an unknown, silently-ignored `default` would suddenly become an assertion failure, creating a breaking change. Perhaps it would be better to use a "soft assertion", we can use a macro such as `NUT_ASSERT_NO_DEFAULT()` to generate a warning message instead:

    WARNING: Unexpected `default` condition occurred driver.c, line 123, please file a bug report!

The problem of true developer-mode assertions is that they're rarely enabled in production systems, missing many opportunity to catch bugs.

**Comment by jimklimov** [comment]
Yeah, such a loud log message (maybe in all builds, not just developer) does make sense and is minimally invasive in terms of functionality. Except when it thrashes logging I/O and storage, as in #1358 (just shy of 4 years to eventual resolution, hopefully) :)

And it can lead to bugs getting known and addressed anyhow.
