### ISSUE TITLE
Support for the multimatic / Edelstrom MD2000 over serial port?

### ISSUE THREAD

**Issue by Stevehans** [networkupstools/nut#2688]
I have one of these, it's got a serial port and from the German docs the speed is 2400, but I'm having no luck discovering what the protocol is.

Does anyone have any ideas?

**Comment by Stevehans** [comment]
Found it to be nutdrv_qx, similar to a megatec.

**Comment by jimklimov** [comment]
Thanks for the hint. If you can post a data dump (e.g. data listing from `upsc`, perhaps commands abd tunables from `upscmd` and `upsrw`) - that would be quite welcome.
