### ISSUE TITLE
nutclient compilation warning

### ISSUE THREAD

**Issue by balooloo** [networkupstools/nut#269]
Hello all,

@aquette point me the following compilation warning:

```
../../../clients/nutclient.cpp:1310:3: warning: delete called on 'nut::Client' that is abstract but has non-virtual destructor [-Wdelete-non-virtual-dtor]
                delete (nut::Client*)client;
                ^
1 warning generated.
```

**Comment by balooloo** [comment]
F#####g text editor which transform tab into spaces automatically.
I will redo a PR for that.

**Comment by clepple** [comment]
Looks good to me. Is there any code that tests this?

**Comment by balooloo** [comment]
No. This is a trivial patch.
But I am looking for create tests in #227.
