### ISSUE TITLE
[HCL] Liebert PSP supported by usbhid-ups

### ISSUE THREAD

**Issue by SilentT-FR** [networkupstools/nut#296]
root@pi:/lib/nut# upsc LiebertBox@maison
Init SSL without certificate database
battery.charge: 100
battery.charge.low: 38
battery.charge.warning: 38
battery.type: PbAc
battery.voltage: 13.7
battery.voltage.nominal: 12.0
device.mfr: Emerson Network Power
device.model: LiebertPSP
device.serial:
device.type: ups
driver.name: usbhid-ups
driver.parameter.pollfreq: 30
driver.parameter.pollinterval: 2
driver.parameter.port: /dev/bus/usb/001/005
driver.version: 2.7.2
driver.version.data: Belkin HID 0.16
driver.version.internal: 0.38
input.frequency: 49.9
input.voltage: 235.6
output.voltage: 234.4
ups.load: 1
ups.mfr: Emerson Network Power
ups.model: LiebertPSP
ups.productid: 0001
ups.serial:
ups.status: OL CHRG
ups.vendorid: 10af

http://www.emersonnetworkpower.com/en-US/Products/ACPower/DesktopWorkstationUPS/Pages/liebertpspstandbyups350650va.aspx

root@pi:/lib/nut# dpkg -s nut
Package: nut
Status: install ok installed
Priority: optional
Section: metapackages
Installed-Size: 233
Maintainer: Arnaud Quette aquette@debian.org
Architecture: all
Version: 2.7.2-4
Depends: nut-server, nut-client
Description: network UPS tools - metapackage
 Network UPS Tools (NUT) is a client/server monitoring system that
 allows computers to share uninterruptible power supply (UPS) and
 power distribution unit (PDU) hardware. Clients access the hardware
 through the server, and are notified whenever the power status
 changes.
 .
 This package is a metapackage that installs both nut-server and nut-client,
 in most cases it is sufficient for a basic UPS monitoring system.
Homepage: http://www.networkupstools.org/

**Comment by clepple** [comment]
Does shutdown work properly?

**Comment by clepple** [comment]
@SilentT-FR assuming that shutdown works; please open another issue if not.
