### ISSUE TITLE
nut-driver.service after network.target?

### ISSUE THREAD

**Issue by bigon** [networkupstools/nut#313]
Hi,

I was reviewing a bit the boot sequence on my machine today, and I was wondering, why is nut-driver.service adding a After=network.target, does anybody remember the rational behind this?

The drivers are local only right? Shouldn't this be removed?

**Comment by aquette** [comment]
hi Laurent,
some drivers are local (serial, USB), some are networked (SNMP, XML/HTTP, IPMI), and the communication between upsd and the client (upsmon at least) are over the network (either localhost or remote, if upsmon is in slave mode).

So the answer is not that easy, and there is no simple rule to address that.

**Comment by bigon** [comment]
OK, nevermind then
