### ISSUE TITLE
apcsmart driver option(s?) ignored

### ISSUE THREAD

**Issue by dark-penguin** [networkupstools/nut#322]
Some APC UPS-es ignore the "Kill power now!" command if power is already back at the moment.

According to man ups.conf and man apcsmart.conf, it's possible to specify "sdtype = 4" option in ups.conf to use an "CS hack" to work around this. (There is even an example in man ups.conf with this very option!)

Unfortunately, it does not work. Even with "sdtype = 4" specified, issuing "/sbin/upsdrvctl shutdown" (which is called after the shutdown procedure to kill the power) does NOT use the hack (which would be to start a simulated power failure to switch to battery power before issuing the forced shutdown command). It just sends a normal shutdown command, which is ignored.

However, issuing "upscmd -u myuser -p mypwd apc shutdown.return cs" does work as described in the manual (namely, you must issue this command TWICE, the second time being 3~15 sec after the first one.)

**Comment by clepple** [comment]
@msoltyspl, any thoughts?

**Comment by msoltyspl** [comment]
Dunno yet, I'll doublecheck this later today and see how it looks in the code.

**Comment by msoltyspl** [comment]
Ok, sorry for delay.

It seems that sdcmd_CS() doesn't do any wait in between commands (but still works fine if it's called twice manually).

We can add say arbitrary 3.5 seconds to wait after the first (force ob) command is being issued. This should work finein that case.

**Comment by msoltyspl** [comment]
I've pushed the changes to master, please verify when you have the chance if it's working correctly for you.

**Comment by dark-penguin** [comment]
Thank you!
I'm not sure when I'll be around that server, but I'll try it someday.
For the record, which version has the fix? I'd be interested in tracking when it makes its way into Debian Sid.

**Comment by aquette** [comment]
@dark-penguin : since the changes are in master, the next stable (2.7.5) will have it... when published.
