### ISSUE TITLE
Powercom: Detection is failing

### ISSUE THREAD

**Issue by ikus060** [networkupstools/nut#356]
In Powercom driver the detection of the UPS is not working because the first read is failing too often. So the detection of the UPS is not really working. To workarround this, it's possible to read twice. See log bellow:

```
$ sudo ./powercom -D -D -D -D -D -q -a powercom1
Network UPS Tools - PowerCom protocol UPS driver 0.17 (2.7.4.1)
   0.000000	[D5] send_to_all: SETINFO driver.parameter.port "/dev/ttyUSB0"
   0.000104	[D5] send_to_all: SETINFO driver.parameter.type "KIN"
   0.000200	[D1] debug level is '5'
   0.002995	[D2] Flow control disable
   0.003244	[D5] Num of bytes requested for reading from UPS: 16
   3.150724	data receiving error (0 instead of 16 bytes)
```

Updating the line 972 from `if (!ups_getinfo()) return;` to `if (!ups_getinfo() && !ups_getinfo()) return;` is solving the issue and the detection of UPS is always working.

**Comment by jimklimov** [comment]
Thanks for the idea, and sorry it was noticed earlier. PR posted to productize it :)
