### ISSUE TITLE
Developer manual: fix typo and formatting in subdriver commands

### ISSUE THREAD

**Issue by clepple** [networkupstools/nut#436]
http://buildbot.networkupstools.org/~buildbot/docker-debian-jessie/docs/latest//docs/developer-guide.chunked/ar01s04.html#_writing_a_subdriver has a command that ends in `auto` - should be `-a auto`. Also fix formatting of surrounding paragraphs with commands.

**Comment by clepple** [comment]
Correction: after 8e94b560 , should be `-s ups` or something.

**Comment by aquette** [comment]
indeed, the command in the subdriver chapter is still sticking with the old approach, where we were not requiring an ups.conf entry. So "-s" is more suitable.
Then for the note on needed version to support "-s", that may also affect some other ones...
I'll check how what to do.
