### ISSUE TITLE
404 error on SNMP protocol link

### ISSUE THREAD

**Issue by clepple** [networkupstools/nut#444]
http://lists.alioth.debian.org/pipermail/nut-upsdev/2017-June/007287.html :

> when I go to : http://networkupstools.org/docs/man/snmp-ups.html and click on the link at the bottom: http://www.networkupstools.org/protocols/snmp/ I get a 404 error.

Should be http://networkupstools.org/ups-protocols.html#_snmp

Can we do a redirect from protocols/snmp/ ?

**Comment by clepple** [comment]
fixed in ea589cde1c - close after the website has been updated.

**Comment by jimklimov** [comment]
Works right with the html-man pages built to the current (rolling-release since recently) website.
