### ISSUE TITLE
Wanted: autoconf tests for C++11 abilities and flags

### ISSUE THREAD

**Issue by jimklimov** [networkupstools/nut#472]
Following from #466 discussion, there are parts of the codebase (e.g. cppunit tests) that require C++11 support. Depending on compilers, it may be available by default, or require certain `CXXFLAGS` tuning, or be missing altogether (so that part of code should not be built). The `configure` script and `Makefile`s should be amended to figure this out properly.

**Comment by clepple** [comment]
Related: #366
