### ISSUE TITLE
nut-scanner: nutscan_init() called before nut_debug_level is set; library scan messages are hidden

### ISSUE THREAD

**Issue by clepple** [networkupstools/nut#500]
`nut_debug_level` starts out as 0, but the `-D` flags are not parsed until after `nutscan_init()` is called. Therefore, it is not possible to see the debug messages when searching for libraries.

Tested with https://github.com/networkupstools/nut/tree/libusb-1.0%2B0.1 @ 80bc452.

Noticed while debugging #499.

**Comment by bigon** [comment]
https://github.com/networkupstools/nut/pull/502 is merged, shouldn't this bug be closed?
