### ISSUE TITLE
Add autoconf check for libusb_strerror()

### ISSUE THREAD

**Issue by clepple** [networkupstools/nut#509]
As mentioned in https://github.com/networkupstools/nut/issues/300#issuecomment-309431300 (and [on nut-upsuser](http://lists.alioth.debian.org/pipermail/nut-upsuser/2017-June/010765.html)), libusb-1.0.9 does not have `libusb_strerror()`.

If this function is not found, recommend the use of libusbx instead.

**Comment by clepple** [comment]
I hate to keep adding to the list for 2.7.5, but RHEL6 is still supported for a while.

**Comment by aquette** [comment]
ticket will be closed once we merge the libusb1 PR
