### ISSUE TITLE
CyberPower CP900EPFCLCD showing incorrect output voltage

### ISSUE THREAD

**Issue by owennelson** [networkupstools/nut#581]
Using the usbhid-ups driver my CP900EPFCLCD reports the output voltage as being between 260 and 270 - though it sits at 260 most of the time.  The input voltage averages around 240 as would be expected.

Running the driver directly (/usr/local/libexec/nut/usbhid-ups -DDD -a ups) results in the following voltage information:

   0.010678     Report[get]: (3 bytes) => 0f ef 00                                                                                  
   0.010687     Path: UPS.Input.Voltage, Type: Feature, ReportID: 0x0f, Offset: 0, Size: 16, Value: 239                             
...
   0.011178     Report[get]: (3 bytes) => 12 ef 00                                                                                  
   0.011188     Path: UPS.Output.Voltage, Type: Feature, ReportID: 0x12, Offset: 0, Size: 16, Value: 260 

I'm not entirely sure what to make of this, though it would appear that ef (239) is somehow being interpreted as 260?

Extra note: Configured through FreeNAS's UI and set to CP1000PFCLCD as it's the closest option - not sure if this makes any difference.

**Comment by clepple** [comment]
Probably the same as this issue: https://github.com/networkupstools/nut/issues/439

**Comment by serfriz** [comment]
Any update on this? My CyberPower CP1500PFCLCD shows an output.voltage of 142.0

**Comment by alexruffell** [comment]
My PR1000RTXL2U reports faulty measurements in battery and output voltages:

`battery.charge: 100
battery.voltage: 2.4
battery.voltage.nominal: 22`

However the LCD panel shows the voltage at around 48V. The correct input/output line voltage is 120V for where I am located but the UPS reports:

`
input.voltage: 122.0
input.voltage.nominal: 120
output.voltage: 253.0
`
and likely unrelated to this issue, it also reports:

`ups.status: OL`

which I am guessing means OverLoad, which it definitely is not.

**Comment by flashydave** [comment]
OL means ONLINE not OverLoad!

**Comment by flashydave** [comment]
As mentiondd above the output voltage issue IS identical to [#439](https://github.com/networkupstools/nut/issues/439)  and is now fixed subject to merging.

Regarding the battery voltage CPS are aware there are some issues and have fixed at least one of them on  new production models. Sadly they said on cheaper models their firmware is not  field upgradeable to fix existing users.

**Comment by alexruffell** [comment]
I wonder whether they include my $600-700 UPS in that group. I will check to see if there is a firmware upgrade but as far as I recall I never saw one for the UPS itself, just the RMCard.

**Comment by flashydave** [comment]
I'm not sure the extent of any similarities between CPS products or code construction.  I was trying to fix my CP900EPFCLCD battery and output voltage reporting and they confirmed back to me the points I made above.

**Comment by techniker** [comment]
I have the same issue here where the output voltage is reported as 260-262V.

**Comment by flashydave** [comment]
On 19:29, Mon 09 Oct 23, Bjoern Heller wrote:
> I have the same issue here where the output voltage is reported as 260-262V.
What version of software are you running as this was fixed some time
ago.  

If you like you can run the driver under debug where logging will show
you that it has detected the erroneous MIB data reported by the UPS and corrected it.

That might tell us what is going on.

**Comment by alexruffell** [comment]
> I have the same issue here where the output voltage is reported as 260-262V.

In my case it turned out to be a firmware bug as my UPS died weeks before the warranty was up and CyberPower replaced it. The brand new UPS never had the issue so it must have had something to do with the UPS' firmware and not the RMCARD205 as that one stayed the same. I think my old UPS had firmware 1.6xx and the new one came with 1.9xx (but I'd have to check to be sure).

**Comment by jimklimov** [comment]
PR #2718 is presumed to have fixed the broken CPS input/output voltage reports discussed in this issue.
