### ISSUE TITLE
[SOLVED] POWERCOM RPT-600AP unable to set battery.charge.*

### ISSUE THREAD

**Issue by bikrus** [networkupstools/nut#634]
Hi!
### Issue
Either of `battery.charge.*` in `/etc/nut/ups.conf` doesn't work even after reboot.

Related comment: [@clepple wrote: For the last item, what does ups.conf look like? ...](https://github.com/networkupstools/nut/issues/633#issuecomment-433629013)

```ini
maxretry = 3
[RPT-600AP]
        driver = usbhid-ups
        port = auto
        vendorid = 0d9f
        battery.charge.low: 70
        battery.charge.warning: 80
```
```ini
maxretry = 3
[RPT-600AP]
        driver = usbhid-ups
        port = auto
        vendorid = 0d9f
        ignorelb
        override.battery.charge.low: 70
        override.battery.charge.warning: 80
```
The output of `upsc RPT-600AP` still show old values
```console
$ upsc RPT-600AP
...
battery.charge.low: 10
battery.charge.warning: 30
...
```

> In case of missing some valuable info - please, point me.

### Product info
**Related product report**: [[HCL] POWERCOM RPT-600AP supported by usbhid-ups](https://github.com/networkupstools/nut/issues/633)

**Comment by bikrus** [comment]
Sorry. My mistake. Instead of ` = ` I have misstyped ` : ` in param set. Next config snippet does work.
```ini
[RPT-600AP]
        driver = usbhid-ups
        port = auto
        vendorid = 0d9f
        ignorelb
        override.battery.charge.low = 70
        override.battery.charge.warning = 80
```
```console
$ upsc RPT-600AP
...
battery.charge.low: 70
battery.charge.warning: 80
...
```

**Comment by clepple** [comment]
Glad that worked!
