### ISSUE TITLE
missing apcupsd variables

### ISSUE THREAD

**Issue by fernandolcx** [networkupstools/nut#752]
Some variables are missing in upsc when using apcupsd-nut driver, like `LOAD_W`, `LOAD_VA` and `OUTCURNT`.

Is this a lack from the driver itself, or there's something I can do to show them?

**Comment by clepple** [comment]
It is possible that the user who contributed the driver didn't have those variables to test. Here is the full mapping from apcupsd to NUT names: https://github.com/networkupstools/nut/blob/master/drivers/apcupsd-ups.h#L97

If you can recompile NUT and test, we'd be happy to take a patch or pull request to add the missing variables.

**Comment by fernandolcx** [comment]
Check #753

**Comment by fernandolcx** [comment]
Solved in commit f096d98

Thanks!
