### ISSUE TITLE
CyberPower CP1000PFCLCD Incorrect battery.voltage

### ISSUE THREAD

**Issue by EHCanadian** [networkupstools/nut#768]
The CyberPower CP1000PFCLCD displays as a 24v dc system when it is a 12v dc

battery.voltage 24.0
battery.voltage.nominal 24

This should read 14.4 dc max with a 13.8 dc as charged

**Comment by clepple** [comment]
According to CyberPower, `battery.voltage` is not supported on other UPSes in the PFCLCD family, so I assume this is the case for your UPS as well: https://github.com/networkupstools/nut/issues/459#issuecomment-325163688
