### ISSUE TITLE
 How to set it to realize automatic shutdown when battery is used, and then close ups

### ISSUE THREAD

**Issue by HeiSeven** [networkupstools/nut#816]
How to set it to realize automatic shutdown when battery is used, and then close ups

**Comment by jimklimov** [comment]
Did you read the fine manual? The short summary is that you should configure a device section in `ups.conf` do define which driver fits your UPS, and set up the `upsmon.conf` or a more flexible but difficult `upssched` to react to different states of the device, such as on-battery + low-battery. Then you set up the NUT UPS driver, NUT Server (upsd) and the NUT monitoring client (e.g. upsmon) for autostart.
