### ISSUE TITLE
usbhid-ups does not disable beeper with Eaton 3S550

### ISSUE THREAD

**Issue by aquette** [networkupstools/nut#9]
Alioth bug #313884
http://lists.alioth.debian.org/pipermail/nut-upsuser/2012-October/007994.html

**Comment by stalchuk** [comment]
Hi Arnaud,
any news on the issue?

Have being using Eaton 3S700 facing the same issue:
-nut-2.7.4 (compiled from source)
-linux-2.4.28 (uClibc 0.9.27)
-libusb-0.1.12 (compiled from source)

Please let me know, if any debugging info is required. So far **OK** is returned, but beeper is not disabled:
`1) upsc 3s ups.beeper.status
enabled
2) upscmd -uMyUser -pMyPassord 3s beeper.disable
OK
3) upsc 3s ups.beeper.status
enabled`

**Comment by aquette** [comment]
Hi Sergey / @stalchuk 
just to say that I'm looking at it and think I've found the issue. However, I'll need a bit more time to test my findings and implement it in a way that does not generate regression for other units.
This will have to happen by the end of this (busy) week, since I'm on training next one and part of the following...

**Comment by aquette** [comment]
Thanks for your patience Sergey!

**Comment by stalchuk** [comment]
Thanks for the fix, Arnaud!

Now it works as expected)

**Comment by jimklimov** [comment]
@aquette: any progress on this one? I suppose the least that can be done is a driver config option to use this or that HID path (as a string? As enum?) if several are available? Or all of them if available? Or just try all and let unimplemented ones be ignored?..
