### ISSUE TITLE
Devices Dumps Library improvements

### ISSUE THREAD

**Issue by aquette** [networkupstools/nut#93]
NUT Devices Dumps Library (http://networkupstools.org/ddl/) needs some more actions before being complete:
- [x] Reference on the website Compatibility page (@aquette)
- [x] Reference on the website Documentation page (@aquette)
- [x] Create a dedicated repository (http://networkupstools.org/ddl/) and website (http://networkupstools.org/ddl/)
- [x] Create a better page, or set of pages, to document / search / submit dumps ( @zykh, would you be able to help?)
- [x] Harvest the web and NUT mailing lists for existing devices dumps (@zykh addressed that)

Postponed items
- Complete task #94 (NUT Dummy driver Gen3)
- Call to users for massive report (who?) => or make it easier to submit DDL report.
Part of this was started to be addressed with https://github.com/networkupstools/nut/commit/ca9f6019a7d05ea23762610c55c935db50ee0c88

**Comment by clepple** [comment]
@aquette, this is the last issue on our list before releasing 2.7.3. Anything else we need to do here? Should we split any features off into separate issues?

**Comment by aquette** [comment]
@clepple: everything seems good. I've merged the other remaining PR for 2.7.3.
We can proceed to releasing 2.7.3. Anything else will wait for the next point release (2.7.4)

**Comment by aquette** [comment]
I think this ticket is good to be closed.
@clepple and @zykh : anything I missed?

**Comment by clepple** [comment]
Looks good to me. Since we have some old URLs at the beginning of this ticket, it should be mentioned that the final location is http://networkupstools.org/ddl/ <http://networkupstools.org/ddl/>

**Comment by aquette** [comment]
@cleppe: thanks ;) I've updated the description to list the final locations, for both the website and the github repository. Now closing the ticket
