### ISSUE TITLE
nut_debug_level does not propagate to libnutscan from nut-scanner

### ISSUE THREAD

**Issue by Bi11** [networkupstools/nut#935]
This issue was introduced by f82e78ec0c0b1f2a45cf52cc37ee44bd246cc1d3.

Currently there are two instances of `nut_debug_level`, one in nut-scanner, another in libnutscan. 
`-DDD` can not raise debug level of libnutscan.

**Comment by jimklimov** [comment]
Thanks! I wonder if I added to confusion, or just overlooked, with recent
fixes for symbol visibility (static for file-private scope as lint
suggested). Maybe an extra copy should be deleted and an extern declared in
header.

**Comment by jimklimov** [comment]
Should be fixed by #1160
