### ISSUE TITLE
Problem with all numbers either being rounded up or truncated to integer

### ISSUE THREAD

**Issue by denisyurin** [networkupstools/nut#977]
Hi there, 

I have a problem with NUT that it rounds up all UPS digital data to integer values. I have an Eaton 9SX 6000iR with a Network M2 card with Environmental Sensor connected to it. Using Web-interface I can see that Temperature and Humidity data goes at least with one decimal place precision. However when I receive this data from the card with NUT’s snmp-ups driver and display it with upsc and other nut’s tools, all numbers either rounded up or truncated to integer. Here is my setup:

Ubuntu Server 20.04.2
nut 2.7.4 (standard ubuntu package)
[Eaton 9SX 6000iR](http://powerquality.eaton.com/9SX6KiRT.aspx?cx=22&GUID=A1D30D0B-49CE-4B33-A08A-7C6C52D1733E) + [Eaton Network M2 card](https://www.eaton.com/us/en-us/catalog/backup-power-ups-surge-it-power-distribution/eaton-gigabit-network-card---na.html) + [Eaton Environmental Monitoring Probe Gen 2](https://www.eaton.com/us/en-us/catalog/backup-power-ups-surge-it-power-distribution/eaton-environmental-monitoring-probe-gen-2.html)

```
/etc/nut/ups.conf

[snmpv1]
        driver = snmp-ups
        port = 192.168.0.8
        community = public
        snmp_version = v1
        pollfreq = 15
```

```
> uspc snmpv1
ambient.humidity: 25.00
ambient.humidity.high: 90.00
ambient.humidity.low: 10.00
ambient.temperature: 22.0
ambient.temperature.high: 80.00
ambient.temperature.low: 0.00
…
```

Any help is extremely welcome!

UPDATE: checked it with latest NUT build, the same issue: values are continued to be rounded to integer

```
ambient.humidity: 6
ambient.humidity.high: 90
ambient.humidity.low: 10
ambient.temperature: 17.0
ambient.temperature.high: 30
ambient.temperature.low: 0
battery.charge: 100
battery.charger.status: resting
battery.current: 0
battery.date: 07/18/2024
battery.runtime: 280
battery.runtime.low: 180
battery.voltage: 199
device.mfr: EATON
device.model: Eaton 9SX 6000i
device.serial: G201K38021
device.type: ups
driver.name: snmp-ups
driver.parameter.pollfreq: 15
driver.parameter.pollinterval: 2
driver.parameter.port: 192.168.0.8
driver.parameter.snmp_version: v1
driver.parameter.synchronous: no
driver.version: 2.7.4-2124-g9defa7a9
driver.version.data: pw MIB 0.92
driver.version.internal: 1.15

```
UPDATE 2: checked the precision of temperature and humidity readings reported by SNMP directly. 

`snmpwalk -v1 -c public 192.168.0.8 -m "EATON-EMP-MIB" iso.3.6.1.4.1.534.1.6`

```
EATON-OIDS::xupsEnvironment.1.0 = INTEGER: 26
EATON-EMP-MIB::xupsEnvRemoteTemp.0 = INTEGER: 20 degrees Centigrade
EATON-EMP-MIB::xupsEnvRemoteHumidity.0 = INTEGER: 27 percent
EATON-EMP-MIB::xupsEnvNumContacts.0 = INTEGER: 2
EATON-EMP-MIB::xupsContactIndex.1 = INTEGER: 1
EATON-EMP-MIB::xupsContactIndex.2 = INTEGER: 2
EATON-EMP-MIB::xupsContactType.1 = INTEGER: notUsed(4)
EATON-EMP-MIB::xupsContactType.2 = INTEGER: notUsed(4)
EATON-EMP-MIB::xupsContactState.1 = INTEGER: open(1)
EATON-EMP-MIB::xupsContactState.2 = INTEGER: open(1)
EATON-EMP-MIB::xupsContactDescr.1 = STRING: EMPDT1H1C2 @1-C1
EATON-EMP-MIB::xupsContactDescr.2 = STRING: EMPDT1H1C2 @1-C2
EATON-EMP-MIB::xupsEnvRemoteTempLowerLimit.0 = INTEGER: 0 degrees Centigrade
EATON-EMP-MIB::xupsEnvRemoteTempUpperLimit.0 = INTEGER: 80 degrees Centigrade
EATON-EMP-MIB::xupsEnvRemoteHumidityLowerLimit.0 = INTEGER: 10 percent
EATON-EMP-MIB::xupsEnvRemoteHumidityUpperLimit.0 = INTEGER: 90 percent
```
There is no decimal digits. So, this is not a NUT problem. This is how the card's firmware exposes sensors data via SNMP-protocol.  It seems that that Eaton software engineers do not care much about precision. BAD!

**Comment by masterwishx** [comment]
@denisyurin Hi, do you still have Eaton 9sx?

**Comment by denisyurin** [comment]
Yes, I do.

**Comment by masterwishx** [comment]
> Yes, I do.

Maybe you using eco mode or only online ?
I'm almost finished pr for enabling bypass and eco mode for Eaton.
Tested with my 9E 2000i and entered to eco, but some commands sometime not work for me do some issues on my side but would be cool if someone can test it also

**Comment by masterwishx** [comment]
Oh you are not using usb...

**Comment by denisyurin** [comment]
Regarding my problem I found a solution (thanks to Eaton engineers): new Eaton MIBs have a branch .1.3.6.1.4.1.534.6.8 where the humidity and temperature are given with 0.1 precision

**Comment by jimklimov** [comment]
...and OIDs from those MIB branches are present in many current NUT SNMP mapping tables.
